import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { getFormalRoomArtworkTextureSize } from '../src/museum/formal-room/artworks'
import {
  MUSEUM_BASE_LIGHTING,
  MUSEUM_LIGHTING_BUDGET,
  museumToneMappingExposure,
  OPENING_SALON_ARCHITECTURAL_LIGHTS,
  OPENING_SALON_ARTWORK_LIGHTS,
} from '../src/museum/formal-room/museumLighting'

function source(path: string) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

describe('Formal Museum Room MVP', () => {
  it('ships three linked animated museum defaults behind a reusable artwork contract', () => {
    const artworks = source('../src/museum/formal-room/artworks.ts')

    expect(artworks).toContain("id: 'yes-yes'")
    expect(artworks).toContain("id: 'enjoyables-official'")
    expect(artworks).toContain("id: 'curated-hearts'")
    expect(artworks.match(/animationKind: 'image'/g)).toHaveLength(3)
    expect(artworks.match(/sourceUrl: 'https:\/\//g)).toHaveLength(3)
    expect(artworks).toContain("orientation: 'landscape'")
    expect(artworks.match(/frameSize: \[/g)).toHaveLength(3)
    expect(artworks).toContain('THREE.CanvasTexture')
  })

  it('keeps the room art-first while letting owned wallet art replace the samples', () => {
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const desk = source('../src/museum/formal-room/CollectionDesk.tsx')
    const route = source('../app/api/opensea/owned-nfts/route.ts')

    expect(room).toContain('artworks.map')
    expect(room).toContain('meshBasicMaterial map={texture} toneMapped={false}')
    expect(room).toContain("event.code === 'Escape'")
    expect(room).toContain('createFormalRoomWalletExhibition')
    expect(room).toContain('Your exhibition is ready')
    expect(desk).toContain('verifyOwnedSelection')
    expect(desk).toContain('Preview in room')
    expect(route).toContain('process.env.OPENSEA_API_KEY')
    expect(route).not.toContain('NEXT_PUBLIC_OPENSEA')
  })

  it('uses frame-shaped high-resolution canvases and room-sized proxy images', () => {
    const artworks = source('../src/museum/formal-room/artworks.ts')
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')

    expect(getFormalRoomArtworkTextureSize([1.72, 2.24], 1024)).toEqual([786, 1024])
    expect(getFormalRoomArtworkTextureSize([3.05, 2.08], 2048)).toEqual([2048, 1397])
    expect(artworks).toContain("context.imageSmoothingQuality = 'high'")
    expect(artworks).toContain('texture.colorSpace = THREE.SRGBColorSpace')
    expect(artworks).toContain('texture.minFilter = THREE.LinearMipmapLinearFilter')
    expect(room).toContain('size.width <= 700 ? 1024 : 2048')
    expect(room).toContain("formalRoomArtworkMediaUrl(sources[sourceIndex], 'room')")
    expect(room).toContain("mediaUrl.startsWith(BUNDLED_FORMAL_ROOM_MEDIA_PREFIX)")
    expect(room).toContain('artwork.thumbnailUrl')
    expect(room).toContain('nextImage.onerror')
    expect(room).toContain('ARTWORK_IMAGE_LOAD_TIMEOUT_MS = 15_000')
    expect(room).toContain('() => advanceToNextSource(nextImage)')
    expect(room).toContain('clearLoadTimer()')
    expect(room).toContain('paintFormalRoomArtworkError(texture, artwork.accent)')
    expect(artworks).toContain('ARTWORK UNAVAILABLE')
    expect(room).toContain("onMediaStatus(artwork.id, 'error')")
  })

  it('keeps a crisp poster while safely playing optional animated NFT media', () => {
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const playback = source('../src/museum/formal-room/mediaPlayback.ts')

    expect(room).toContain("formalRoomArtworkMediaUrl(motionUrl, 'motion')")
    expect(room).toContain('ownedNftMediaProxyUrl(mediaUrl, variant)')
    expect(room).toContain('new THREE.VideoTexture(nextVideo)')
    expect(room).toContain('nextVideo.muted = true')
    expect(room).toContain('nextVideo.loop = true')
    expect(room).toContain('nextVideo.playsInline = true')
    expect(room).toContain('appendChild(nextVideo)')
    expect(room).toContain('video.remove()')
    expect(room).toContain('paintFormalRoomArtworkImage(texture, nextVideo, artwork.accent)')
    expect(room.match(/paintFormalRoomArtworkImage\(texture, nextImage, artwork\.accent\)/g)).toHaveLength(2)
    expect(room).toContain("motionSurface === 'image'")
    expect(room).toContain("appendChild(nextImage)")
    expect(room).toContain('image.remove()')
    expect(room).toContain("motionSurface === 'image' || motionSurface === 'decoded-image'")
    expect(room).toContain('new ImageDecoder')
    expect(room).toContain('decodedFrameIndexRef')
    expect(room).toContain("motionSurface === 'video' && videoTexture && !reducedMotion")
    expect(room).toContain('shouldPaintFormalRoomAnimationFrame')
    expect(room).toContain("publishMotionStatus('unavailable')")
    expect(room).toContain('posterStatus === \'ready\' || optionalMotionStatus === \'ready\'')
    expect(playback).toContain('FORMAL_ROOM_ANIMATED_IMAGE_MAX_FPS = 15')
    expect(playback).toContain('FORMAL_ROOM_ANIMATED_IMAGE_MOBILE_LONG_EDGE = 768')
    expect(playback).toContain('FORMAL_ROOM_ANIMATED_IMAGE_DESKTOP_LONG_EDGE = 1024')
  })

  it('starts directly in exploration with a quiet three-area menu', () => {
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const camera = source('../src/museum/formal-room/FormalRoomCameraRig.tsx')
    const walkMath = source('../src/museum/formal-room/walkMath.ts')
    const salonLighting = room.slice(
      room.indexOf('function SalonLighting'),
      room.indexOf('function GalleryWallDisplay'),
    )
    const pictureLamp = room.slice(
      room.indexOf('function PictureLamp'),
      room.indexOf('function SalonPlannedSpotlight'),
    )

    expect(room).toContain("const mode: FormalRoomViewMode = 'explore'")
    expect(room).toContain("data-room-mode={mode}")
    expect(room).not.toContain('<strong>Walk Museum</strong>')
    expect(room).not.toContain('Enter the museum galleries')
    expect(room).not.toContain('Museum Highlights')
    expect(room).not.toContain('Salon View')
    expect(room).not.toContain('Return to the opening composition')
    expect(room).not.toContain('onClick={enterExplore}')
    expect(room).toContain('className={styles.minimalChrome}')
    expect(room).toContain('styles.museumMenuButton')
    expect(room).toContain('aria-controls="museum-area-menu"')
    expect(room).toContain('<strong>Main Museum</strong>')
    expect(room).toContain('<strong>Courtyard</strong>')
    expect(room).toContain('<strong>Burn Room</strong>')
    expect(room).toContain('styles.walletButton')
    expect(room).toContain("'Connect Wallet'")
    expect(room).toContain("walletConnected ? 'My Atrium' : 'Connect Wallet'")
    const openWallet = room.slice(room.indexOf('const openWallet'), room.indexOf('const applyAtriumInstallation'))
    expect(openWallet).toContain('openAtriumRegistry()')
    expect(openWallet).not.toContain('openCollectionDesk()')
    expect(room).toContain('walkInputRef.current.travelRequested = MUSEUM_GALLERY_BY_ID.lobby.travelPose')
    expect(room).not.toContain('className={styles.exitLink}')
    expect(room).not.toContain('className={styles.roomTitle}')
    expect(room).not.toContain('className={styles.artDock}')
    expect(room).not.toContain('className={styles.walkHelpButton}')
    expect(room).not.toContain('Enter the gallery circuit')
    expect(room).not.toContain('Four doors · one loop')
    expect(room).not.toContain('Finish loop')
    expect(room).not.toContain('tap a room name to hop there')
    expect(room).toContain('<SalonEntrance />')
    expect(room).toContain('<MuseumExpansion')
    expect(room).toContain("<SalonLighting active={activeMuseumArea === 'lobby'} />")
    expect(room).toContain('activeMuseumArea={activeMuseumArea}')
    expect(room).not.toContain('aria-label="Museum room navigator"')
    expect(room).not.toContain('className={styles.museumNavigator}')
    expect(room).not.toContain('showWalkHelp')
    expect(salonLighting).not.toContain('<directionalLight')
    expect(salonLighting).not.toContain('<pointLight')
    expect(salonLighting).not.toContain('THREE.AdditiveBlending')
    expect(pictureLamp).not.toContain('<coneGeometry')
    expect(pictureLamp).toContain('THREE.NormalBlending')
    expect(salonLighting.indexOf('{active ? (')).toBeLessThan(salonLighting.indexOf('OPENING_SALON_ARTWORK_LIGHTS.map'))
    expect(salonLighting.indexOf('<hemisphereLight')).toBeLessThan(salonLighting.indexOf('{active ? ('))
    expect(MUSEUM_BASE_LIGHTING.ambient.intensity).toBeGreaterThanOrEqual(0.36)
    expect(MUSEUM_BASE_LIGHTING.ambient.intensity).toBeLessThanOrEqual(0.42)
    expect(MUSEUM_BASE_LIGHTING.hemisphere.intensity).toBeGreaterThanOrEqual(0.6)
    expect(MUSEUM_BASE_LIGHTING.hemisphere.intensity).toBeLessThanOrEqual(0.68)
    expect(museumToneMappingExposure(390)).toBeGreaterThan(museumToneMappingExposure(768))
    expect(museumToneMappingExposure(768)).toBeGreaterThan(museumToneMappingExposure(1440))
    expect(room).toContain('<MuseumRendererLighting />')
    expect(OPENING_SALON_ARTWORK_LIGHTS).toHaveLength(3)
    expect(OPENING_SALON_ARCHITECTURAL_LIGHTS).toHaveLength(1)
    expect(MUSEUM_LIGHTING_BUDGET.openingSalonActiveLights).toBe(4)
    expect(camera.match(/export function FormalRoomCameraRig/g)).toHaveLength(1)
    expect(camera).toContain("mode === 'explore'")
    expect(camera).toContain('reviewPose?.yaw ?? Math.PI')
    expect(camera).toContain('capFormalWalkDelta')
    expect(camera).toContain('suppressArtworkClickUntil')
    expect(camera).toContain('beginFormalJump')
    expect(camera).toContain('stepFormalJumpState')
    expect(camera).toContain('jumpStateRef.current.height')
    expect(camera).toContain('__setMuseumCapturePose')
    expect(camera).toContain("get('capture') === '1'")
    expect(room).toContain("event.code === 'Space'")
    expect(room).not.toContain('className={styles.walkHud}')
    expect(room).not.toContain('aria-label="Explore museum controls"')
    expect(room).toContain('className={styles.mobileJumpButton}')
    expect(walkMath).toContain('resolveFormalWalkPosition')
    expect(walkMath).toContain('FORMAL_WALK_COLLIDERS')
  })

  it('adds one clear, functional courtyard entrance to the west museum link', () => {
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const expansion = source('../src/museum/formal-room/MuseumExpansion.tsx')
    const camera = source('../src/museum/formal-room/FormalRoomCameraRig.tsx')
    const courtyardRoute = source('../app/courtyard/page.tsx')

    expect(room).toContain("router.push('/courtyard')")
    expect(room).toContain('onOpenCourtyard={openCourtyard}')
    expect(room).toContain('Open the courtyard')
    expect(expansion).toContain('<CourtyardGardenDoor x={-9.2} onOpen={onOpenCourtyard} />')
    expect(expansion).toContain("userData={{ courtyardDoor: true, href: '/courtyard', label: 'Courtyard' }}")
    expect(expansion).toContain("context.fillText('COURTYARD'")
    expect(expansion).not.toContain('<ConnectorGardenWindow x={-9.2} />')
    expect(camera).toContain("review === 'courtyard-door'")
    expect(camera).toContain("process.env.NODE_ENV === 'production'")
    expect(courtyardRoute).toContain('defaultSpawn="museum"')
  })

  it('adds a distinct Burn Room entrance, preserves the east window, and hands off to the live burn app', () => {
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const expansion = source('../src/museum/formal-room/MuseumExpansion.tsx')
    const camera = source('../src/museum/formal-room/FormalRoomCameraRig.tsx')
    const burnRoomRoute = source('../app/burn-room/page.tsx')

    expect(room).toContain("router.push('/burn-room')")
    expect(room).toContain('onOpenBurnRoom={openBurnRoom}')
    expect(room).toContain('Open the Burn Room')
    expect(expansion).toContain('<BurnRoomDoorAndWindow x={9.2} onOpen={onOpenBurnRoom} />')
    expect(expansion).toContain("userData={{ burnRoomDoor: true, href: '/burn-room', label: 'Burn Room' }}")
    expect(expansion).toContain("context.fillText('BURN ROOM'")
    expect(expansion).toContain("userData={{ burnRoomWindow: true, view: 'winter-garden' }}")
    expect(expansion).not.toContain('<ConnectorGardenWindow x={9.2} winter />')
    expect(camera).toContain("review === 'burn-room-door'")
    expect(camera).toContain('return { x: 9.2, z: 6.5, yaw: 0 }')
    expect(burnRoomRoute).toContain("https://burn.museumofbased.art/")
    expect(burnRoomRoute).toContain('redirect(BURN_ROOM_URL)')
  })

  it('provides route metadata plus loading and recovery surfaces', () => {
    const layout = source('../app/formal-room/layout.tsx')
    const loading = source('../app/formal-room/loading.tsx')
    const error = source('../app/formal-room/error.tsx')

    expect(layout).toContain("title: 'Museum of Based Art'")
    expect(layout).toContain("themeColor: '#214844'")
    expect(loading).toContain('Opening the Main Museum')
    expect(loading).toContain('Preparing the exhibition lights')
    expect(error).toContain('The tiny electrician is embarrassed.')
    expect(error).toContain('reset')
  })
})
