import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

function source(path: string) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

describe('Museum mobile experience', () => {
  it('makes the Main Museum the site entrance and keeps travel choices behind one small menu', () => {
    const homeRoute = source('../app/page.tsx')
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const styles = source('../src/museum/formal-room/FormalMuseumRoom.module.css')

    expect(homeRoute).toContain('return <FormalMuseumRoom />')
    expect(homeRoute).toContain('ssr: false')
    expect(homeRoute).not.toContain('redirect(')
    expect(homeRoute).not.toContain('HomePage')
    expect(room).toContain('aria-label="Museum areas"')
    expect(room).toContain('<strong>Main Museum</strong>')
    expect(room).toContain('<strong>Courtyard</strong>')
    expect(room).toContain('<strong>Burn Room</strong>')
    expect(room).not.toContain('<strong>Wardrobe</strong>')
    expect(room).toContain('styles.walletButton')
    expect(room).not.toContain('Museum Highlights')
    expect(room).toContain('data-testid="museum-welcome"')
    expect(room).toContain('aria-modal="true"')
    expect(room).toContain('<strong>Enter Museum</strong>')
    expect(room).toContain('<strong>How to Move</strong>')
    expect(styles).toContain('.minimalChrome')
    expect(styles).toContain('.museumMenuPanel')
    expect(styles).toContain('.welcomeScrim')
    expect(styles).toContain('.welcomePanel')
    expect(styles).toContain('.welcomeEnter:focus-visible')
    expect(styles).toContain('.museumMenuButton:focus-visible')
    expect(styles).toContain('@media (prefers-reduced-motion: reduce)')
  })

  it('keeps public museum rooms free of developer recording and lab controls', () => {
    const recorder = source('../src/home/SceneRecorderControls.tsx')
    const labSwitcher = source('../src/ui/DevLabSwitcher.tsx')

    expect(recorder).toContain("['/', '/courtyard', '/burn-room', '/wardrobe', '/formal-room'].includes(pathname)")
    expect(labSwitcher).toContain("pathname === '/vacuum-lab'")
    expect(labSwitcher).not.toContain("pathname === '/' || pathname === '/vacuum-lab'")
  })

  it('keeps the Formal Room public, touch-friendly, and free of dev recording controls', () => {
    const homeRoute = source('../app/page.tsx')
    const legacyRoute = source('../app/formal-room/page.tsx')
    const room = source('../src/museum/formal-room/FormalMuseumRoom.tsx')
    const joystick = source('../src/museum/formal-room/MobileMovementJoystick.tsx')
    const camera = source('../src/museum/formal-room/FormalRoomCameraRig.tsx')
    const collectionDesk = source('../src/museum/formal-room/CollectionDesk.tsx')
    const styles = source('../src/museum/formal-room/FormalMuseumRoom.module.css')
    const collectionStyles = source('../src/museum/formal-room/CollectionDesk.module.css')

    expect(homeRoute).toContain('ssr: false')
    expect(legacyRoute).toContain("redirect('/')")
    expect(room).toContain('data-testid="formal-museum-room"')
    expect(room).toContain("const mode: FormalRoomViewMode = 'explore'")
    expect(room).toContain('aria-label="Open museum menu"')
    expect(room).toContain('aria-controls="museum-area-menu"')
    expect(room).toContain('aria-label="Mobile walking controls"')
    expect(room).toContain('<MobileMovementJoystick')
    expect(room).toContain('Swipe anywhere')
    expect(room).toContain('Left stick walks · swipe anywhere to look around')
    expect(room).toContain('aria-describedby="museum-mobile-controls-description"')
    expect(room).toContain('aria-label="Directional movement alternatives"')
    expect(room).toContain('const sceneBlocked = welcomeOpen || modalOpen')
    expect(room).toContain('const walkBlocked = sceneBlocked || museumMenuOpen')
    expect(room).toContain('inert={sceneBlocked ? true : undefined}')
    expect(room).toContain('label="Walk forward"')
    expect(room).toContain('onKeyDown={handleKeyDown}')
    expect(room).toContain('onClick={handleAccessibleClick}')
    expect(room).not.toContain('formal-room-walk-help')
    expect(room).toContain('onPointerCancel={handlePointerRelease}')
    expect(room).toContain('onLostPointerCapture={handlePointerRelease}')
    expect(joystick).toContain('resolveFormalJoystickInput')
    expect(joystick).toContain('setPointerCapture(event.pointerId)')
    expect(joystick).toContain('onPointerCancel={handlePointerRelease}')
    expect(joystick).toContain('onLostPointerCapture={handlePointerRelease}')
    expect(joystick).toContain('window.addEventListener(\'orientationchange\', resetJoystick)')
    expect(camera).toContain('if (touchPointerId !== null) return')
    expect(camera).toContain('if (touchPointerId !== event.pointerId) return')
    expect(camera).toContain('resolveFormalCursorSteer')
    expect(camera).toContain('if (mouseCursorSteer.active)')
    expect(room).toContain('controlsEnabled={!walkBlocked}')
    expect(camera).not.toContain('!event.isPrimary')
    expect(styles).toContain('@media (max-width: 700px)')
    expect(styles).toContain('@media (max-width: 920px) and (max-height: 610px) and (orientation: landscape)')
    expect(styles).toContain('@media (hover: none) and (pointer: coarse)')
    expect(styles).not.toContain('@media (max-height: 610px) and (min-width: 701px)')
    expect(styles).toContain('.walking .canvasWrap canvas')
    expect(styles).toContain('touch-action: none')
    expect(styles).toContain('@media (prefers-reduced-motion: reduce)')
    expect(styles).toContain('.mobileJoystickPad')
    expect(styles).toContain('.mobileLookGuideVisible')
    expect(styles).not.toContain('.mobileDpad')
    expect(room).toContain('Your exhibition is ready')
    expect(room).toContain('className={styles.previewMiniActions}')
    expect(room).toContain('previewPreparingMedia || previewHasMediaError')
    expect(styles).toContain('.previewMiniActions')
    expect(collectionDesk).toContain('nft.thumbnailUrl ?? nft.imageUrl')
    expect(collectionDesk).toContain("ownedNftMediaProxyUrl(thumbnailUrl, 'thumb')")
    expect(collectionDesk).toContain('className={styles.slotTopline}')
    expect(collectionDesk).toContain('className={styles.slotMotionBadge}')
    expect(collectionDesk).toContain('className={styles.motionBadge}')
    expect(collectionDesk).toContain('Moves in the room')
    expect(collectionDesk).toContain('isOwnedNftDisplayable')
    expect(collectionDesk).toContain('ref={slotTrayRef}')
    expect(collectionDesk).toContain('revealSlot(activeSlot)')
    expect(collectionDesk).toContain('slotRefs.current[index] = node')
    expect(collectionStyles).toContain('height: 100dvh')
    expect(collectionStyles).toContain('scroll-snap-type: x mandatory')
    expect(collectionStyles).toContain('overscroll-behavior-x: contain')
    expect(collectionStyles).toContain('@media (max-width: 320px) and (orientation: portrait)')
    expect(collectionStyles).toContain('flex-basis: 140px')
    expect(collectionStyles).toContain('.motionArtworkPlaceholder')
    expect(collectionStyles).toContain('.motionBadge')
    expect(collectionStyles).toContain('@media (max-height: 610px) and (orientation: landscape)')
    expect(collectionStyles).toContain('@media (max-width: 700px) and (max-height: 610px) and (orientation: landscape)')
    expect(collectionStyles).not.toContain('@media (max-height: 610px) and (min-width: 701px)')
    expect(collectionStyles).toContain('grid-template-columns: repeat(2')
    expect(styles).toContain('width: min(230px, calc(100vw - 16px))')
  })

  it('provides mobile movement and lobby navigation in the courtyard', () => {
    const courtyardRoute = source('../app/courtyard/page.tsx')
    const courtyard = source('../docs/asset-generation/preview/pogo-orb-v2/control.tsx')
    const museumNav = source('../src/ui/MuseumMobileNav.tsx')
    const styles = source('../app/globals.css')

    expect(courtyardRoute).toContain('<MuseumMobileNav roomName="Sunny Courtyard" />')
    expect(courtyard).toContain('aria-label="Mobile movement controls"')
    expect(courtyard).toContain('aria-label="Move character"')
    expect(courtyard).toContain('mobile-action-jump')
    expect(styles).toContain('.control-room-polished .mobile-controls')
    expect(styles).toContain('.courtyardControlsIntro')
    expect(museumNav).toContain("event.key !== 'Escape'")
    expect(museumNav).toContain("router.push('/')")
    expect(museumNav).toContain('Main Museum')
  })

  it('uses the player-safe burn room and keeps its dev switch in the dev route', () => {
    const burnRoute = source('../app/burn-room/page.tsx')
    const devRoute = source('../app/vacuum-asset/page.tsx')
    const burnRoom = source('../src/vacuum/VacuumAssetInspect.tsx')

    expect(burnRoute).toContain("BURN_ROOM_URL = 'https://burn.museumofbased.art/'")
    expect(burnRoute).toContain('redirect(BURN_ROOM_URL)')
    expect(devRoute).toContain('<VacuumAssetInspect />')
    expect(burnRoom).toContain('!playerMode ? (')
  })

  it('uses a dedicated three-row phone header in the museum wardrobe', () => {
    const wardrobe = source('../docs/asset-generation/preview/red-shell/display.tsx')
    const styles = source('../docs/asset-generation/preview/red-shell/display.css')

    expect(styles).toContain('.museumWardrobeRoute .display-room-app')
    expect(styles).toContain('grid-template-rows: 152px minmax(0, 1fr)')
    expect(styles).toContain('.museumWardrobeRoute .room-mode-switch')
    expect(styles).toContain('.museumWardrobeRoute .quick-search')
    expect(styles).toContain('@media (max-width: 900px) and (max-height: 560px)')
    expect(wardrobe).toContain("window.location.assign('/')")
    expect(wardrobe).toContain('Exit to Lobby')
  })
})
