import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { PRODUCTION_TUNING } from '../src/core/productionTuning'
import {
  PRODUCTION_DEV_MODES,
  deriveStretchSnapGrappleState,
  deriveSuctionContactState,
  getProductionDevMode,
  isProductionDevModeId,
} from '../src/dev/productionDevModes'
import { computeVisibleSlimeVacuumability } from '../src/experiment/slimePhysics'

const experimentLabSource = readFileSync(new URL('../src/experiment/ExperimentLab.tsx', import.meta.url), 'utf8')
const experimentMaterialsSource = readFileSync(new URL('../src/experiment/experimentMaterials.tsx', import.meta.url), 'utf8')

describe('production dev scaffold', () => {
  it('keeps experiment materials split out of the gameplay monolith', () => {
    expect(experimentMaterialsSource).toContain('export function createBagPulseMaterial')
    expect(experimentMaterialsSource).toContain('export function createSlimeSurfaceMaterial')
    expect(experimentMaterialsSource).toContain('export function ExperimentOutlineMesh')
    expect(experimentLabSource).toContain("from './experimentMaterials'")
    expect(experimentLabSource).not.toContain('function createBagPulseMaterial')
    expect(experimentLabSource).not.toContain('function createSlimeSurfaceMaterial')
  })

  it('exposes the required focused modes', () => {
    expect(PRODUCTION_DEV_MODES.map((mode) => mode.id)).toEqual([
      'full-loop',
      'movement-lab',
      'suction-contact',
      'glug-rhythm',
      'deep-embed',
      'pivot-swing-lab',
      'grip-swing-lab',
      'hose-swing',
      'reattach-chain',
      'multi-glob-chain',
      'slime-material',
      'bag-fill',
    ])
  })

  it('falls back to full-loop for unknown mode requests', () => {
    expect(isProductionDevModeId('suction-contact')).toBe(true)
    expect(isProductionDevModeId('wrong-source')).toBe(false)
    expect(getProductionDevMode('wrong-source').id).toBe('full-loop')
  })

  it('maps live telemetry into the suction contact state sequence', () => {
    expect(deriveSuctionContactState(null)).toBe('free-motion')
	    expect(deriveSuctionContactState({ slimePhysics: { avgEasySuctionPull: 0.02 } })).toBe('airflow-influence')
	    expect(deriveSuctionContactState({ bridgeActive: true, bridgeLength: 0.7, bridgeThickness: 0.16 })).toBe('flow-bridge-forming')
	    expect(deriveSuctionContactState({ slimeSealStrength: 0.5 })).toBe('seal-contact')
	    expect(deriveSuctionContactState({ sealQuality: 0.54 })).toBe('seal-contact')
    expect(deriveSuctionContactState({ slimeSealStrength: 1.05, hoseHookStrength: 0.8 })).toBe('anchored-suction-grip')
    expect(deriveSuctionContactState({ slimeSealStrength: 1.05, glugEventStrength: 0.3 })).toBe('stretch-and-gulp')
    expect(deriveSuctionContactState({ embedState: 'embed-lock', embedDepth: 0.48, sealQuality: 1.02 })).toBe('anchored-suction-grip')
    expect(deriveSuctionContactState({ pivotLocked: true, pivotTension: 0.42 })).toBe('anchored-suction-grip')
    expect(deriveSuctionContactState({ pivotLocked: true, pivotTension: 1.05 })).toBe('tension-and-snap')
    expect(deriveSuctionContactState({ gripActive: true, gripDizzy: 0.3 })).toBe('stretch-and-gulp')
    expect(deriveSuctionContactState({ gripActive: true, gripDizzy: 0.92 })).toBe('tension-and-snap')
    expect(deriveSuctionContactState({ embedState: 'embed-strain', embedDepth: 0.62, swingTension: 0.9 })).toBe('tension-and-snap')
    expect(deriveSuctionContactState({ embedState: 'pop-out-snap', embedFleckBurst: 0.5 })).toBe('fling-and-recovery')
    expect(deriveSuctionContactState({ slimeSealStrength: 1.05, glugMassFlow: 0.2 })).toBe('stretch-and-gulp')
    expect(deriveSuctionContactState({ swingTension: 1.3 })).toBe('tension-and-snap')
    expect(deriveSuctionContactState({ tetherRelease: 0.3 })).toBe('fling-and-recovery')
    expect(deriveSuctionContactState({ postSnapReattachTimer: 0.3 })).toBe('fling-and-recovery')
    expect(deriveSuctionContactState({ hoseSlimeInteractionPhase: 'near' })).toBe('airflow-influence')
    expect(deriveSuctionContactState({ hoseSlimeInteractionPhase: 'touch' })).toBe('seal-contact')
    expect(deriveSuctionContactState({ hoseSlimeInteractionPhase: 'gulp' })).toBe('stretch-and-gulp')
    expect(deriveSuctionContactState({ hoseSlimeInteractionPhase: 'strain' })).toBe('tension-and-snap')
    expect(deriveSuctionContactState({ hoseSlimeInteractionPhase: 'pop' })).toBe('fling-and-recovery')
  })

  it('maps live telemetry into the stretch-snap grapple state sequence', () => {
    expect(deriveStretchSnapGrappleState(null)).toBe('free')
    expect(deriveStretchSnapGrappleState({ suctionReadiness: 0.08 })).toBe('seeking')
    expect(deriveStretchSnapGrappleState({ suctionState: 'prePull' })).toBe('prePull')
    expect(deriveStretchSnapGrappleState({ suctionState: 'contact' })).toBe('contact')
    expect(deriveStretchSnapGrappleState({ suctionState: 'sealed', anchorTension: 0.05 })).toBe('sealed')
    expect(deriveStretchSnapGrappleState({ suctionState: 'sealed', anchorTension: 0.4 })).toBe('stretched')
    expect(deriveStretchSnapGrappleState({ suctionState: 'releasing', anchorPopJuice: 0.4 })).toBe('snapping')
    expect(deriveStretchSnapGrappleState({ anchorReattachGraceTimer: 0.5 })).toBe('graceReattach')
    expect(deriveStretchSnapGrappleState({ anchorReattachCatchPulse: 0.3 })).toBe('caught')
  })

  it('keeps production tuning values named and non-zero', () => {
    expect(PRODUCTION_TUNING.movement.bodyMass).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.cruiseForce).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.bodyDamping).toBeLessThan(0.15)
    expect(PRODUCTION_TUNING.movement.maxSpeed).toBeGreaterThan(6)
    expect(PRODUCTION_TUNING.movement.acceleration).toBeGreaterThan(30)
    expect(PRODUCTION_TUNING.movement.deceleration).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.deceleration).toBeLessThan(0.2)
    expect(PRODUCTION_TUNING.movement.lateralFriction).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.lateralFriction).toBeLessThan(0.12)
    expect(PRODUCTION_TUNING.movement.driftRetention).toBeGreaterThan(0.95)
    expect(PRODUCTION_TUNING.movement.driftRetention).toBeLessThan(0.99)
    expect(PRODUCTION_TUNING.movement.turnResponsiveness).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.turnResponsiveness).toBeLessThan(3)
    expect(PRODUCTION_TUNING.movement.velocityFacingBlend).toBeGreaterThan(0.7)
    expect(PRODUCTION_TUNING.movement.velocityFacingBlend).toBeLessThan(0.9)
    expect(PRODUCTION_TUNING.movement.speedBoostFromInputChange).toBeGreaterThan(0.65)
    expect(PRODUCTION_TUNING.movement.reverseRebound).toBeGreaterThan(0.45)
    expect(PRODUCTION_TUNING.movement.cameraSpeedLead).toBe(0)
    expect(PRODUCTION_TUNING.movement.cameraMaxLead).toBe(0)
    expect(PRODUCTION_TUNING.movement.cameraLeadSmoothing).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.pointerSteeringAssist).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.pointerBrakeStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.pointerBrakeStrength).toBeLessThan(0.12)
    expect(PRODUCTION_TUNING.movement.pointerLateralDamping).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.pointerLateralDamping).toBeLessThan(0.1)
    expect(PRODUCTION_TUNING.movement.keyboardAcceleration).toBeGreaterThan(PRODUCTION_TUNING.movement.cruiseForce)
    expect(PRODUCTION_TUNING.movement.keyboardTargetLead).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.movement.keyboardNoInputBrake).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.keyboardNoInputBrake).toBeLessThan(0.012)
    expect(PRODUCTION_TUNING.movement.mouseBodyTranslationEnabled).toBe(false)
    expect(PRODUCTION_TUNING.movement.mouseBodyAcceleration).toBe(0)
    expect(PRODUCTION_TUNING.movement.mouseBodyTargetLead).toBe(0)
    expect(PRODUCTION_TUNING.movement.mouseBodyControlInfluence).toBe(0)
    expect(PRODUCTION_TUNING.movement.mouseBodyHookedScale).toBe(0)
    expect(PRODUCTION_TUNING.movement.mouseBodySealedScale).toBe(0)
    expect(PRODUCTION_TUNING.movement.mouseBodyRotationEnabled).toBe(false)
    expect(PRODUCTION_TUNING.movement.hoseAimTurnRate).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimIdleTurnRate)
    expect(PRODUCTION_TUNING.movement.hoseAimPointResponsiveness).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimContactResponsiveness)
    expect(PRODUCTION_TUNING.movement.hoseAimContactResponsiveness).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimIdleResponsiveness)
    expect(PRODUCTION_TUNING.movement.hoseAimDeadZone).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseAimMaxSpeed).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimContactMaxSpeed)
    expect(PRODUCTION_TUNING.movement.hoseAimStabilityLagLimit).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimDeadZone)
    expect(PRODUCTION_TUNING.movement.hoseAimJitterFallDamping).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimJitterRiseDamping)
    expect(PRODUCTION_TUNING.movement.hoseAimNoiseCalm).toBeGreaterThan(0.75)
    expect(PRODUCTION_TUNING.movement.hoseAimMouthWiggleCalm).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimNoiseCalm)
    expect(PRODUCTION_TUNING.movement.hoseAimBodyReachMin).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseAimBodyReachMax).toBeLessThanOrEqual(0.65)
    expect(PRODUCTION_TUNING.movement.hoseAimBodyReachMax).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimBodyIdleReach)
    expect(PRODUCTION_TUNING.movement.hoseAimBodyIdleReach).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimBodyReachMin)
    expect(PRODUCTION_TUNING.movement.hoseAimBodyIdleReach).toBeLessThanOrEqual(0.24)
    expect(PRODUCTION_TUNING.movement.hoseReachOffsetForward).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseReachMinDistance)
    expect(PRODUCTION_TUNING.movement.hoseReachRadius).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseReachSideLimit)
    expect(PRODUCTION_TUNING.movement.hoseReachRadius).toBeGreaterThan(1.2)
    expect(PRODUCTION_TUNING.movement.hoseReachMinDistance).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseReachMaxDistance).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimBodyReachMax)
    expect(PRODUCTION_TUNING.movement.hoseReachMaxDistance).toBeGreaterThan(1.4)
    expect(PRODUCTION_TUNING.movement.hoseReachMaxDistance).toBeLessThanOrEqual(1.7)
    expect(PRODUCTION_TUNING.movement.hoseReachSideLimit).toBeLessThan(PRODUCTION_TUNING.movement.hoseReachMaxDistance)
    expect(PRODUCTION_TUNING.movement.hoseReachBackwardLimit).toBeLessThan(PRODUCTION_TUNING.movement.hoseReachOffsetForward)
    expect(PRODUCTION_TUNING.movement.hoseBodyUnlatchMinForward).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseReachMinDistance)
    expect(PRODUCTION_TUNING.movement.hoseBodyUnlatchMinForward).toBeLessThan(PRODUCTION_TUNING.movement.hoseReachOffsetForward)
    expect(PRODUCTION_TUNING.movement.hoseBodyUnlatchMinDistance).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseReachOffsetForward)
    expect(PRODUCTION_TUNING.movement.hoseBodyUnlatchMinDistance).toBeLessThan(PRODUCTION_TUNING.movement.hoseReachMaxDistance * 0.3)
    expect(PRODUCTION_TUNING.movement.hoseBodyUnlatchSideClearance).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.movement.hoseBodyUnlatchSideClearance).toBeLessThan(PRODUCTION_TUNING.movement.hoseReachSideLimit)
    expect(PRODUCTION_TUNING.movement.hoseReachSmoothing).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseReturnSpeed)
    expect(PRODUCTION_TUNING.movement.hoseElasticLag).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseMouthMaxSpeed).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseAimContactMaxSpeed)
    expect(PRODUCTION_TUNING.movement.hoseScreenReachDeadZonePx).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseScreenReachMaxPx).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseScreenReachDeadZonePx)
    expect(PRODUCTION_TUNING.movement.hoseMouseReachStrength).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseMouseBendStrength)
    expect(PRODUCTION_TUNING.movement.hoseScreenReachMaxPx).toBeGreaterThan(260)
    expect(PRODUCTION_TUNING.movement.hoseVisualBaseLength).toBeLessThanOrEqual(0.55)
    expect(PRODUCTION_TUNING.movement.hoseCartoonBendStart).toBeLessThan(0.25)
    expect(PRODUCTION_TUNING.movement.hoseCartoonBendEase).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseCartoonBendRelaxation).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.movement.hoseCartoonBendRelaxation).toBeLessThan(0.5)
    expect(PRODUCTION_TUNING.movement.hoseCartoonBendSmoothingPasses).toBeGreaterThanOrEqual(1)
    expect(PRODUCTION_TUNING.movement.hoseCartoonStretchArcLift).toBeGreaterThan(0.08)
    expect(PRODUCTION_TUNING.movement.hoseCartoonStretchSideBow).toBeGreaterThan(0.04)
    expect(PRODUCTION_TUNING.movement.hoseEyeSpread).toBeGreaterThan(0.11)
    expect(PRODUCTION_TUNING.movement.hoseEyeSpread).toBeLessThan(0.15)
    expect(PRODUCTION_TUNING.movement.hoseEyeLift).toBeGreaterThan(0.13)
    expect(PRODUCTION_TUNING.movement.hoseEyeGoofyScale).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.movement.hoseEyeGoofyScale).toBeLessThan(1.1)
    expect(PRODUCTION_TUNING.movement.hoseEyeWonk).toBeLessThan(0.02)
    expect(PRODUCTION_TUNING.movement.hosePupilCross).toBeGreaterThan(0.01)
    expect(PRODUCTION_TUNING.movement.hosePupilCross).toBeLessThan(0.025)
    expect(PRODUCTION_TUNING.movement.hosePupilDumbDrift).toBeGreaterThan(0.004)
    expect(PRODUCTION_TUNING.movement.hosePupilDumbDrift).toBeLessThan(0.01)
    expect(PRODUCTION_TUNING.movement.hoseBrowGoofyTilt).toBeGreaterThan(0.1)
    expect(PRODUCTION_TUNING.movement.hoseCheekSpread).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseEyeSpread)
    expect(PRODUCTION_TUNING.movement.hoseCheekScale).toBe(0)
    expect(PRODUCTION_TUNING.movement.hoseSmileWidth).toBeGreaterThan(0.08)
    expect(PRODUCTION_TUNING.movement.hoseSmileWidth).toBeLessThan(PRODUCTION_TUNING.movement.hoseEyeSpread)
    expect(PRODUCTION_TUNING.movement.hoseContactDamping).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseContactSpring)
    expect(PRODUCTION_TUNING.movement.hoseContactSettleDamping).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.hoseContactVelocityLimit).toBeLessThan(0.6)
    expect(PRODUCTION_TUNING.movement.hoseContactOffsetLimit).toBeLessThan(0.6)
    expect(PRODUCTION_TUNING.movement.hoseContactVelocityLimit).toBeLessThan(0.2)
    expect(PRODUCTION_TUNING.movement.hoseContactOffsetLimit).toBeLessThan(0.3)
    expect(PRODUCTION_TUNING.movement.hoseContactWildnessCalm).toBeGreaterThan(0.9)
    expect(PRODUCTION_TUNING.movement.hoseContactFrontWhipCalm).toBeGreaterThan(PRODUCTION_TUNING.movement.hoseContactWildnessCalm)
    expect(PRODUCTION_TUNING.movement.hoseContactHighFrequencyCalm).toBeGreaterThan(0.9)
    expect(PRODUCTION_TUNING.movement.hoseContactWildnessFloor).toBeLessThan(0.05)
    expect(PRODUCTION_TUNING.movement.cameraReadableYawCenter).toBe(Math.PI)
    expect(PRODUCTION_TUNING.movement.cameraReadableIdleYawLimit).toBeLessThan(PRODUCTION_TUNING.movement.cameraReadableHookedYawLimit)
    expect(PRODUCTION_TUNING.movement.cameraReadableHookedYawLimit).toBeLessThan(PRODUCTION_TUNING.movement.cameraReadableAimYawLimit)
    expect(PRODUCTION_TUNING.movement.cameraReadableAimYawLimit).toBeLessThan(Math.PI / 2)
    expect(PRODUCTION_TUNING.movement.cameraReadableHardClampPadding).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.movement.cameraReadableIdleBias).toBeGreaterThan(PRODUCTION_TUNING.movement.cameraReadableAimBias)
    expect(PRODUCTION_TUNING.movement.cameraReadableHookedBias).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.suctionSeekRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
		    expect(PRODUCTION_TUNING.suction.suctionSeekRadius).toBeGreaterThan(3.4)
	    expect(PRODUCTION_TUNING.suction.preContactPullRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
		    expect(PRODUCTION_TUNING.suction.edgeContactForgiveness).toBeGreaterThan(1)
	    expect(PRODUCTION_TUNING.suction.flowBridgeStartDistance).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
	    expect(PRODUCTION_TUNING.suction.flowBridgeMaxLength).toBeGreaterThan(PRODUCTION_TUNING.suction.flowBridgeStartDistance)
	    expect(PRODUCTION_TUNING.suction.flowBridgeBaseThickness).toBeGreaterThan(PRODUCTION_TUNING.suction.flowBridgeMinThickness)
	    expect(PRODUCTION_TUNING.suction.tactileBrushRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.tactileLockRadius)
		    expect(PRODUCTION_TUNING.suction.tactileBrushRadius).toBeGreaterThan(2.4)
		    expect(PRODUCTION_TUNING.suction.tactileLockRadius).toBeGreaterThan(1.2)
	    expect(PRODUCTION_TUNING.suction.tactileBrushPullStrength).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.tactileLockSealStrength).toBeGreaterThan(PRODUCTION_TUNING.suction.tactileBrushSealStrength)
	    expect(PRODUCTION_TUNING.suction.tactileFeedBoost).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceRadiusBase).toBeGreaterThan(0.4)
		    expect(PRODUCTION_TUNING.suction.pileSurfaceMassRadiusMax).toBeGreaterThan(2)
	    expect(PRODUCTION_TUNING.suction.pileSurfacePatchRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius * 0.5)
	    expect(PRODUCTION_TUNING.suction.pileSurfacePatchMassScale).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.pileSurfacePatchMassMax).toBeGreaterThan(0.5)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceBrushReach).toBeGreaterThan(PRODUCTION_TUNING.suction.pileSurfaceLockReach)
		    expect(PRODUCTION_TUNING.suction.pileSurfaceBrushReach).toBeGreaterThan(2.3)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceAssistStrength).toBeGreaterThan(0)
		    expect(PRODUCTION_TUNING.suction.pileSurfaceAssistStrength).toBeGreaterThan(0.85)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceSealStrength).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceFeedBoost).toBeGreaterThan(0)
		    expect(PRODUCTION_TUNING.suction.tinySlimeCandidateFloor).toBeGreaterThan(0.65)
	    expect(PRODUCTION_TUNING.suction.tinySlimeCandidateBonus).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.tinySlimeVisibleMassFloor).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.tinySlimeIntakeTargetFloor).toBeLessThan(0.06)
	    expect(PRODUCTION_TUNING.suction.tinySlimeGlugMassGateFloor).toBeGreaterThan(PRODUCTION_TUNING.suction.tinySlimeVisibleMassFloor)
	    expect(PRODUCTION_TUNING.suction.mouthSurfacePullRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.tactileLockRadius)
	    expect(PRODUCTION_TUNING.suction.mouthContactCompressionDistance).toBeLessThan(PRODUCTION_TUNING.suction.attachmentRadius)
	    expect(PRODUCTION_TUNING.suction.mouthContactCompressionStrength).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.mouthSealRingStrength).toBeGreaterThan(0.5)
	    expect(PRODUCTION_TUNING.suction.mouthAnchorBiteStrength).toBeGreaterThan(PRODUCTION_TUNING.suction.stickySealReleaseStrength)
	    expect(PRODUCTION_TUNING.suction.mouthFloatingDistanceWarn).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.physicalContactDistance).toBeLessThan(PRODUCTION_TUNING.suction.mouthFloatingDistanceWarn)
    expect(PRODUCTION_TUNING.suction.physicalContactGraceDistance).toBeGreaterThan(PRODUCTION_TUNING.suction.physicalContactDistance)
    expect(PRODUCTION_TUNING.suction.physicalReattachContactDistance).toBeGreaterThan(PRODUCTION_TUNING.suction.physicalContactDistance)
    expect(PRODUCTION_TUNING.suction.contactPhysicsGateMin).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.contactPhysicsGateMin).toBeLessThan(0.18)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceContactGraceDistance).toBeGreaterThan(PRODUCTION_TUNING.suction.physicalContactDistance)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceContactGraceDistance).toBeGreaterThan(0.85)
    expect(PRODUCTION_TUNING.suction.pileSurfaceVerticalContactDistance).toBeGreaterThan(PRODUCTION_TUNING.suction.mouthFloatingDistanceWarn)
    expect(PRODUCTION_TUNING.suction.suctionTargetHoldSeconds).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.looseFragmentFlowRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.looseFragmentSwallowRadius)
	    expect(PRODUCTION_TUNING.suction.looseFragmentFlowRadius).toBeGreaterThan(3)
    expect(PRODUCTION_TUNING.suction.looseFragmentSwallowRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.physicalContactDistance)
    expect(PRODUCTION_TUNING.suction.looseFragmentFlowStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.looseFragmentFeedStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.looseFragmentMassDrain).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.looseFragmentHoverDamping).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.looseFragmentMaxFlowSpeed).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.looseFragmentBagMassScale).toBeLessThan(0.35)
    expect(PRODUCTION_TUNING.suction.allVisibleSlimeVacuumableModel).toBe('no-fake-residue-small-slime-field-v4')
    expect(PRODUCTION_TUNING.suction.slimeVacuumableVisibleThreshold).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.slimeVacuumableVisibleThreshold).toBeLessThan(PRODUCTION_TUNING.suction.tinySlimeVisibleMassFloor)
    expect(PRODUCTION_TUNING.suction.slimeSmallPieceSizeThreshold).toBeGreaterThan(0.1)
    expect(PRODUCTION_TUNING.suction.slimeResidueAutoCleanVisibleMass).toBeLessThan(PRODUCTION_TUNING.suction.slimeVacuumableVisibleThreshold)
    expect(PRODUCTION_TUNING.suction.slimeResidueAutoCleanMass).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.slimeResidueMouthPopRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.looseFragmentSwallowRadius)
    expect(PRODUCTION_TUNING.suction.slimeResidueMouthPopPull).toBeGreaterThan(PRODUCTION_TUNING.suction.looseFragmentFlowStrength)
    expect(PRODUCTION_TUNING.suction.slimeResidueMouthPopFeed).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.slimeResidueStuckSeconds).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.slimeResidueBagMassScale).toBeLessThan(PRODUCTION_TUNING.suction.looseFragmentBagMassScale)
    expect(PRODUCTION_TUNING.suction.visibleSlimeSurfacePickupRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.slimeResidueMouthPopRadius)
    expect(PRODUCTION_TUNING.suction.visibleSlimeSurfacePickupRadius).toBeGreaterThan(2)
    expect(PRODUCTION_TUNING.suction.visibleSlimeContactPickupRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.looseFragmentSwallowRadius)
    expect(PRODUCTION_TUNING.suction.visibleSlimeBodyPickupRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.visibleSlimeContactPickupRadius)
    expect(PRODUCTION_TUNING.suction.visibleSlimeSurfacePickupPadding).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.visibleSlimeRelativeDrainScale).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.suction.visualSlimeResidueEnabled).toBe(false)
    expect(PRODUCTION_TUNING.suction.visualSlimeEffectMaxLife).toBeLessThan(0.7)
    expect(PRODUCTION_TUNING.suction.visualSlimeResidueMaxLife).toBeLessThan(PRODUCTION_TUNING.suction.visualSlimeEffectMaxLife)
	    expect(PRODUCTION_TUNING.suction.suctionContactMagnetStrength).toBeGreaterThan(7)
	    expect(PRODUCTION_TUNING.suction.stickySealStrengthThreshold).toBeLessThan(0.52)
	    expect(PRODUCTION_TUNING.glug.gulpMassPerPulse).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.glug.gulpPulseRateMax).toBeGreaterThan(PRODUCTION_TUNING.glug.gulpPulseRateMin)
	    expect(PRODUCTION_TUNING.glug.gulpBridgeSurgeSpeed).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.glug.bagFillPerMass).toBeGreaterThan(0)
	    expect(PRODUCTION_TUNING.suction.targetSwitchMargin).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.arena.radius).toBeGreaterThan(8)
    expect(PRODUCTION_TUNING.arena.playablePadding).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.arena.respawnPadding).toBeGreaterThan(PRODUCTION_TUNING.arena.playablePadding)
    expect(PRODUCTION_TUNING.arena.minimumSlimeSpacing).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.arena.maximumSlimeSpacing).toBeGreaterThan(PRODUCTION_TUNING.arena.minimumSlimeSpacing * 4)
    expect(PRODUCTION_TUNING.arena.clusterCount).toBeGreaterThanOrEqual(4)
    expect(PRODUCTION_TUNING.arena.clusterDensity).toBeGreaterThan(3)
    expect(PRODUCTION_TUNING.arena.isolatedSlimeCount).toBeGreaterThanOrEqual(4)
    expect(PRODUCTION_TUNING.arena.outerRingPlacementBias).toBeGreaterThan(PRODUCTION_TUNING.arena.centerPlacementBias)
    expect(PRODUCTION_TUNING.livingSlime.model).toBe('organic-slime-behaviour-soft-material-v1')
    expect(PRODUCTION_TUNING.livingSlime.idleMotionStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.idleMotionStrength).toBeLessThan(0.45)
    expect(PRODUCTION_TUNING.livingSlime.creepStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.creepStrength).toBeLessThan(0.4)
    expect(PRODUCTION_TUNING.livingSlime.congealStrength).toBeGreaterThan(PRODUCTION_TUNING.livingSlime.breakApartStrength)
    expect(PRODUCTION_TUNING.livingSlime.anchorCrawlRate).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.anchorCrawlRate).toBeLessThan(0.7)
    expect(PRODUCTION_TUNING.livingSlime.anchorCreepRadius).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.livingSlime.maxAnchorDrift).toBeGreaterThan(PRODUCTION_TUNING.livingSlime.anchorCreepRadius)
    expect(PRODUCTION_TUNING.livingSlime.pileBreathStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.lobeFlowStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.contactCalm).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.contactCalm).toBeLessThan(0.7)
    expect(PRODUCTION_TUNING.livingSlime.referencePathStrength).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.livingSlime.referencePathStrength).toBeLessThan(0.9)
    expect(PRODUCTION_TUNING.livingSlime.relocationRadius).toBeGreaterThan(0.8)
    expect(PRODUCTION_TUNING.livingSlime.relocationSnapStrength).toBeLessThan(0.3)
    expect(PRODUCTION_TUNING.livingSlime.mergeWindowStrength).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.livingSlime.splitWindowStrength).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.livingSlime.mergeWindowStrength).toBeGreaterThan(PRODUCTION_TUNING.livingSlime.splitWindowStrength)
    expect(PRODUCTION_TUNING.livingSlime.materialIdleBreathStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.edgeCreepStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.suctionBulgeStrength).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.livingSlime.bridgeOrganicness).toBeGreaterThan(0.3)
    expect(PRODUCTION_TUNING.livingSlime.depletionCrawlStrength).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.livingSlime.recoilSettleStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.internalFlowStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.continuousGenerationModel).toBe('big-slime-colony-multiplication-v7')
    expect(PRODUCTION_TUNING.livingSlime.slimeGenerationEnabled).toBe(true)
    expect(PRODUCTION_TUNING.livingSlime.slimeBaseGrowthRate).toBeGreaterThan(0.15)
    expect(PRODUCTION_TUNING.livingSlime.slimeIgnoredGrowthMultiplier).toBeGreaterThan(2.7)
    expect(PRODUCTION_TUNING.livingSlime.slimeNearVacuumGrowthSuppression).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.livingSlime.slimeSuctionGrowthSuppression).toBeGreaterThan(PRODUCTION_TUNING.livingSlime.slimeNearVacuumGrowthSuppression)
    expect(PRODUCTION_TUNING.livingSlime.slimeSuctionGrowthSuppression).toBeLessThan(0.5)
    expect(PRODUCTION_TUNING.livingSlime.slimeBudThreshold).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.livingSlime.slimeBudThreshold).toBeLessThan(0.03)
    expect(PRODUCTION_TUNING.livingSlime.slimeBudMinMass).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.livingSlime.slimeBudSpawnChance).toBeGreaterThan(4)
    expect(PRODUCTION_TUNING.livingSlime.slimeBudMaxMass).toBeGreaterThan(PRODUCTION_TUNING.livingSlime.slimeBudMinMass)
    expect(PRODUCTION_TUNING.livingSlime.slimeNearCompleteGrowthMultiplier).toBeLessThan(0.25)
    expect(PRODUCTION_TUNING.livingSlime.slimeMaxTotalMassScale).toBeGreaterThan(5.2)
    expect(PRODUCTION_TUNING.blow.model).toBe('hose-reverse-blow-chunk-pusher-v2')
    expect(PRODUCTION_TUNING.blow.enabled).toBe(true)
    expect(PRODUCTION_TUNING.blow.radius).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
    expect(PRODUCTION_TUNING.blow.radius).toBeGreaterThan(5)
    expect(PRODUCTION_TUNING.blow.nearRadius).toBeGreaterThan(2)
    expect(PRODUCTION_TUNING.blow.force).toBeGreaterThan(PRODUCTION_TUNING.suction.preContactPullStrength * 12)
    expect(PRODUCTION_TUNING.blow.coneDotMin).toBeLessThan(0)
    expect(PRODUCTION_TUNING.blow.anchorPushStrength).toBeGreaterThan(PRODUCTION_TUNING.blow.homePushStrength)
    expect(PRODUCTION_TUNING.blow.pilePushStrength).toBeGreaterThan(0.35)
    expect(PRODUCTION_TUNING.blow.chunkPushStrength).toBeGreaterThan(PRODUCTION_TUNING.blow.pilePushStrength)
    expect(PRODUCTION_TUNING.blow.chunkPushMassBoost).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.blow.visualWake).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.blow.maxMoteSpeed).toBeGreaterThan(9)
    expect(PRODUCTION_TUNING.suction.reattachGraceDuration).toBeGreaterThan(PRODUCTION_TUNING.suction.postReleaseControlDampTime)
    expect(PRODUCTION_TUNING.suction.reattachAssistRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
    expect(PRODUCTION_TUNING.suction.reattachAssistRadius).toBeLessThan(PRODUCTION_TUNING.suction.suctionSeekRadius)
    expect(PRODUCTION_TUNING.suction.reattachAssistMaxContactDistance).toBeLessThanOrEqual(PRODUCTION_TUNING.suction.reattachAssistRadius)
    expect(PRODUCTION_TUNING.suction.reattachAssistMinTravelAlignment).toBeGreaterThanOrEqual(0)
    expect(PRODUCTION_TUNING.suction.reattachAssistAngle).toBeGreaterThan(-0.25)
    expect(PRODUCTION_TUNING.suction.reattachAssistAngle).toBeLessThan(0.5)
    expect(PRODUCTION_TUNING.suction.reattachAssistStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachCooldownSameAnchor).toBeGreaterThan(PRODUCTION_TUNING.suction.postReleaseControlDampTime)
    expect(PRODUCTION_TUNING.suction.reattachVelocityBias).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachMinimumExitDistanceFromOldAnchor).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachSameGlobPenalty).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachNewTargetPreference).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachCandidateSwitchMargin).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachCandidateMinScore).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reattachCatchStabilizeTime).toBeGreaterThan(PRODUCTION_TUNING.suction.overstretchHoldTime)
    expect(PRODUCTION_TUNING.suction.stretchSnapStretchedThreshold).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.stretchSnapHighTensionThreshold).toBeGreaterThan(PRODUCTION_TUNING.suction.stretchSnapStretchedThreshold)
    expect(PRODUCTION_TUNING.suction.stretchSnapTensionJuiceScale).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.suction.stretchSnapOrientationRate).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.stretchSnapCameraImpulseScale).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.stretchSnapOrbitSuppression).toBe(1)
    expect(Object.keys(PRODUCTION_TUNING.stretchSnapPresets)).toEqual(['heavySuction', 'rubberSnap', 'arcadeTug'])
    expect(Object.keys(PRODUCTION_TUNING.stretchSnapPresets.heavySuction)).toEqual([
      'springStrength',
      'damping',
      'maxStretch',
      'playerControlWhileSealed',
      'driftRetentionWhileSealed',
      'elasticBounceAmount',
      'snapPower',
      'reattachGraceDuration',
    ])
    expect(PRODUCTION_TUNING.stretchSnapPresets.rubberSnap.maxStretch).toBeGreaterThan(PRODUCTION_TUNING.stretchSnapPresets.heavySuction.maxStretch)
    expect(PRODUCTION_TUNING.stretchSnapPresets.rubberSnap.elasticBounceAmount).toBeGreaterThan(PRODUCTION_TUNING.stretchSnapPresets.heavySuction.elasticBounceAmount)
    expect(PRODUCTION_TUNING.stretchSnapPresets.arcadeTug.playerControlWhileSealed).toBeGreaterThan(PRODUCTION_TUNING.stretchSnapPresets.heavySuction.playerControlWhileSealed)
    expect(PRODUCTION_TUNING.stretchSnapPresets.arcadeTug.reattachGraceDuration).toBeGreaterThan(PRODUCTION_TUNING.stretchSnapPresets.heavySuction.reattachGraceDuration)
    expect(PRODUCTION_TUNING.suction.elasticSpringStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.elasticDamping).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.elasticRestLength).toBeGreaterThan(0.3)
    expect(PRODUCTION_TUNING.suction.elasticMaxStretch).toBeGreaterThan(PRODUCTION_TUNING.suction.elasticRestLength)
    expect(PRODUCTION_TUNING.suction.elasticMaxStretch).toBeLessThanOrEqual(1.5)
    expect(PRODUCTION_TUNING.suction.elasticInputForceWhileSealed).toBeGreaterThan(0.8)
    expect(PRODUCTION_TUNING.suction.playerControlWhileSealed).toBeGreaterThan(0.8)
    expect(PRODUCTION_TUNING.suction.driftRetentionWhileSealed).toBeGreaterThan(0.7)
    expect(PRODUCTION_TUNING.suction.tensionSpeedPenalty).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.reboundBoost).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.elasticBounceAmount).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.bounceFrequency).toBeGreaterThan(PRODUCTION_TUNING.suction.bounceDamping)
    expect(PRODUCTION_TUNING.suction.reboundImpulseScale).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.tensionVelocitySmoothing).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.maxBounceVelocity).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.elasticLateralDamping).toBeGreaterThan(PRODUCTION_TUNING.suction.elasticTangentDamping)
    expect(PRODUCTION_TUNING.suction.elasticMaxRadialForce).toBeGreaterThan(PRODUCTION_TUNING.suction.elasticSpringStrength)
    expect(PRODUCTION_TUNING.suction.elasticTensionRiseDamping).toBeGreaterThan(PRODUCTION_TUNING.suction.elasticTensionFallDamping)
    expect(PRODUCTION_TUNING.suction.latchInfluenceMinSpeed).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.latchInfluenceHoldDelay).toBeLessThan(0.15)
    expect(PRODUCTION_TUNING.suction.latchInfluenceRampTime).toBeLessThan(0.5)
    expect(PRODUCTION_TUNING.suction.latchInfluenceMinSpeed).toBeLessThan(0.1)
    expect(PRODUCTION_TUNING.suction.latchInfluenceTurnStrength).toBeGreaterThan(80)
    expect(PRODUCTION_TUNING.suction.latchInfluenceTangentPreserve).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.suction.latchInfluenceRadialDamping).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.latchInfluenceMaxTangentSpeed).toBeLessThan(PRODUCTION_TUNING.movement.maxSpeed)
    expect(PRODUCTION_TUNING.suction.latchInfluenceMaxTurnForce).toBeGreaterThan(PRODUCTION_TUNING.suction.latchInfluenceTurnStrength)
    expect(PRODUCTION_TUNING.suction.latchInfluenceMotionHoldSeconds).toBeGreaterThan(PRODUCTION_TUNING.suction.latchInfluenceRampTime)
    expect(PRODUCTION_TUNING.suction.latchInfluenceMotionHoldSeconds).toBeLessThan(1.9)
    expect(PRODUCTION_TUNING.suction.latchInfluenceVelocityRedirect).toBeGreaterThan(1.8)
    expect(PRODUCTION_TUNING.suction.latchInfluenceInwardBend).toBeGreaterThan(5)
    expect(PRODUCTION_TUNING.suction.latchInfluencePivotKick).toBeGreaterThan(20)
    expect(PRODUCTION_TUNING.suction.latchInfluenceOffAxisBoost).toBeGreaterThan(4)
    expect(PRODUCTION_TUNING.suction.stickyAnchorHoldStrength).toBeGreaterThan(PRODUCTION_TUNING.suction.stickySealReleaseStrength)
    expect(PRODUCTION_TUNING.suction.stickyAnchorHoldStrength).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.suction.stickyAnchorVisualPulse).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.suction.stickyAnchorDriftTolerance).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.stickyAnchorDriftTolerance).toBeLessThan(0.05)
    expect(PRODUCTION_TUNING.suction.stickyAnchorSealBitePause).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.stickyAnchorDebugMarkerRadius).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.suction.stickyAnchorDebugLineWidth).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.hose.hoseMaxStretch).toBeGreaterThan(PRODUCTION_TUNING.hose.hoseRestLength)
    expect(PRODUCTION_TUNING.hose.hoseMaxStretch).toBeLessThanOrEqual(1.5)
    expect(PRODUCTION_TUNING.hose.anchorRetention).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.embed.embedDepthMax).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.embed.embedSealStrengthMin).toBeLessThan(0.4)
    expect(PRODUCTION_TUNING.embed.embedSurfaceBiteBoost).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.embed.embedSurfaceBiteBoost).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.embed.embedLatchedSubmergeBoost).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.embed.embedLatchedSubmergeBoost).toBeGreaterThan(0.3)
    expect(PRODUCTION_TUNING.embed.embedTipSubmergeScale).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.embed.embedTipLockDepthScale).toBeGreaterThan(0.8)
    expect(PRODUCTION_TUNING.embed.embedTipLockOcclusionScale).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.embed.embedMouthClearanceSink).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldMaxSink).toBeGreaterThan(0.04)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldMaxSink).toBeLessThan(0.12)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldMaxRise).toBeLessThan(0.22)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldFloorClearance).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldPlanarSlack).toBeGreaterThan(0.06)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldPlanarSlack).toBeLessThan(0.16)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldContactPlanarSlack).toBeGreaterThan(PRODUCTION_TUNING.embed.embedMouthWorldPlanarSlack)
    expect(PRODUCTION_TUNING.embed.embedMouthWorldContactPlanarSlack).toBeLessThan(0.24)
    expect(PRODUCTION_TUNING.embed.embedRimOcclusionStrength).toBeGreaterThan(1.4)
    expect(PRODUCTION_TUNING.embed.embedPocketDimpleStrength).toBeGreaterThan(2)
    expect(PRODUCTION_TUNING.embed.embedRimOcclusionStrength).toBeGreaterThan(2)
    expect(PRODUCTION_TUNING.embed.embedSnapThreshold).toBeGreaterThan(PRODUCTION_TUNING.suction.sealBreakTension)
    expect(PRODUCTION_TUNING.embed.embedGlugStrengthMultiplier).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.embed.embedBridgeThicknessMultiplier).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.pivot.pivotRadialPullStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.pivot.pivotTangentialPreserve).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.pivot.freeDamping).toBeLessThan(PRODUCTION_TUNING.movement.bodyDamping)
    expect(PRODUCTION_TUNING.pivot.attachedDamping).toBeGreaterThan(PRODUCTION_TUNING.pivot.freeDamping)
    expect(PRODUCTION_TUNING.pivot.hoseVisualStretchMultiplier).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.pivot.snapFlingImpulseScale).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.pivot.snapFlingImpulseScale).toBeLessThan(1)
    expect(PRODUCTION_TUNING.grip.gripSearchRadius).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
    expect(PRODUCTION_TUNING.grip.rightClickGripEnabled).toBe(false)
    expect(PRODUCTION_TUNING.grip.gripSpinMaxSpeed).toBeGreaterThan(PRODUCTION_TUNING.grip.gripSpinStartSpeed)
    expect(PRODUCTION_TUNING.grip.gripReleaseWindowBase).toBeGreaterThan(PRODUCTION_TUNING.grip.gripReleaseWindowMin)
    expect(PRODUCTION_TUNING.grip.gripPhysicalCueStrength).toBeGreaterThan(PRODUCTION_TUNING.grip.gripRingScaffoldStrength)
    expect(PRODUCTION_TUNING.grip.gripRingScaffoldStrength).toBeLessThan(0.75)
    expect(PRODUCTION_TUNING.grip.gripPocketBiteCueStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.grip.gripMouthAnticipationStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.grip.gripMassTransferMultiplier).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.grip.gripLockSettleSeconds).toBeGreaterThan(PRODUCTION_TUNING.grip.gripReleaseWarmupSeconds)
    expect(PRODUCTION_TUNING.grip.gripLockSuctionImpulse).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.grip.gripOrbitControlStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.grip.gripTangentialForce).toBeLessThan(PRODUCTION_TUNING.grip.gripRadialPullStrength)
    expect(PRODUCTION_TUNING.bag.bagMaxSize).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.bag.bagFillAmountMax).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.bag.bagFillPerMass).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.bag.bagMaxScale).toBeGreaterThan(PRODUCTION_TUNING.bag.bagBaseScale)
    expect(PRODUCTION_TUNING.bag.bagPulseDelay).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.bag.bagFullThreshold).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.bag.bagReactionByGlugMass).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.bag.comboWindowSeconds).toBeGreaterThan(0.75)
    expect(PRODUCTION_TUNING.bag.comboMinStreak).toBeGreaterThanOrEqual(3)
    expect(PRODUCTION_TUNING.bag.comboMaxStreak).toBeGreaterThan(PRODUCTION_TUNING.bag.comboMinStreak)
    expect(PRODUCTION_TUNING.bag.comboMassBoost).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.bag.comboPulseBoost).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.bag.comboShockBoost).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.bag.comboBagScaleBoost).toBeGreaterThan(0.08)
    expect(PRODUCTION_TUNING.bag.comboLabelDuration).toBeGreaterThan(0.6)
    expect(PRODUCTION_TUNING.flow.flowReattachWindowSeconds).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.flow.cleanSnapReattachWindow).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.flow.deadStopDurationThreshold).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.flow.strongSealThreshold).toBeGreaterThan(PRODUCTION_TUNING.flow.weakSealThreshold)
    expect(PRODUCTION_TUNING.flow.flowMetricsEnabled).toBe(true)
    expect(PRODUCTION_TUNING.level.levelClearThreshold).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.levelClearThreshold).toBeLessThan(PRODUCTION_TUNING.level.nearCompleteThreshold)
    expect(PRODUCTION_TUNING.level.majorGlobClearThreshold).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.majorGlobClearThreshold).toBeLessThan(PRODUCTION_TUNING.level.levelClearThreshold)
    expect(PRODUCTION_TUNING.level.completionTriggerDelay).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.discoBeamCount).toBeGreaterThanOrEqual(5)
    expect(PRODUCTION_TUNING.level.discoBeamCount).toBeLessThanOrEqual(9)
    expect(PRODUCTION_TUNING.level.discoBeamPulseRate).toBeGreaterThan(0.8)
    expect(PRODUCTION_TUNING.level.discoBeamPulseRate).toBeLessThan(2)
    expect(PRODUCTION_TUNING.level.discoBeamIntensity).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.level.discoBeamIntensity).toBeLessThan(1.5)
    expect(PRODUCTION_TUNING.level.discoEnergyPulseStrength).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.level.discoEnergyPulseStrength).toBeLessThan(1.5)
    expect(PRODUCTION_TUNING.level.discoReleaseDuration).toBeGreaterThan(PRODUCTION_TUNING.level.completionFreezeDuration)
    expect(PRODUCTION_TUNING.level.bagCompletionPulseStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.completionGlowStrength).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.level.completionGlowStrength).toBeLessThan(1.4)
    expect(PRODUCTION_TUNING.level.partyBuildupStart).toBeLessThan(PRODUCTION_TUNING.level.partyFullAt)
    expect(PRODUCTION_TUNING.level.partyLightingStart).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.partyLightingStart).toBeLessThan(PRODUCTION_TUNING.level.partyLightingFullAt)
    expect(PRODUCTION_TUNING.level.partyLightingMaxOpacity).toBeLessThanOrEqual(0.34)
    expect(PRODUCTION_TUNING.level.backgroundProgressColorStrength).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.backgroundProgressColorStrength).toBeLessThanOrEqual(1)
    expect(PRODUCTION_TUNING.level.backgroundThrobStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.backgroundThrobRate).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.backgroundFinaleBoost).toBeGreaterThan(PRODUCTION_TUNING.level.backgroundThrobStrength)
    expect(PRODUCTION_TUNING.level.backgroundRegenMuteStrength).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.backgroundRegenMuteStrength).toBeLessThan(0.6)
    expect(PRODUCTION_TUNING.level.partyRegenReverseStrength).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.regenStartCompletion).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.regenStartCompletion).toBeLessThan(PRODUCTION_TUNING.level.partyBuildupStart)
    expect(PRODUCTION_TUNING.level.overtakeWarningThreshold).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.level.overtakeWarningThreshold).toBeLessThan(PRODUCTION_TUNING.level.overtakeLossThreshold)
    expect(PRODUCTION_TUNING.level.overtakeLossThreshold).toBe(1)
    expect(PRODUCTION_TUNING.level.overtakeMassWeight).toBeGreaterThan(PRODUCTION_TUNING.level.overtakeRegenWeight)
    expect(PRODUCTION_TUNING.level.overtakeTimeWeight).toBeGreaterThan(0.35)
    expect(PRODUCTION_TUNING.level.overtakeClearRelief).toBeGreaterThan(0.4)
    expect(PRODUCTION_TUNING.level.defeatFloodDuration).toBeGreaterThan(PRODUCTION_TUNING.level.defeatBuildDuration)
    expect(PRODUCTION_TUNING.level.shopBreakDelay).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.currencyGunkScale).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.level.currencyStyleChainValue).toBeGreaterThan(PRODUCTION_TUNING.level.currencyStyleGlugValue)
    expect(PRODUCTION_TUNING.level.regenGraceSeconds).toBeGreaterThanOrEqual(0)
    expect(PRODUCTION_TUNING.level.regenGraceSeconds).toBeLessThan(0.5)
    expect(PRODUCTION_TUNING.level.regenIdleMultiplier).toBeGreaterThan(1.4)
    expect(PRODUCTION_TUNING.level.regenIdleMultiplier).toBeLessThan(2)
    expect(PRODUCTION_TUNING.level.regenBankReviveCost).toBeGreaterThan(0.9)
    expect(PRODUCTION_TUNING.level.cleanupRegenDragScale).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.cleanupRegenDragScale).toBeLessThan(1)
    expect(PRODUCTION_TUNING.level.gunkDangerBaseline).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.level.gunkDangerBaseline).toBeLessThan(0.45)
    expect(PRODUCTION_TUNING.level.gunkCoverageWin).toBeLessThan(0.08)
    expect(PRODUCTION_TUNING.level.gunkCoverageBaseline).toBeCloseTo(PRODUCTION_TUNING.level.gunkDangerBaseline, 3)
    expect(PRODUCTION_TUNING.level.gunkCoverageLoss).toBeGreaterThanOrEqual(0.99)
    expect(PRODUCTION_TUNING.level.gunkCoverageWin).toBeLessThan(PRODUCTION_TUNING.level.gunkCoverageBaseline)
    expect(PRODUCTION_TUNING.level.gunkCoverageBaseline).toBeLessThan(PRODUCTION_TUNING.level.gunkCoverageLoss)
    expect(PRODUCTION_TUNING.level.gunkDangerIdleRiseSeconds).toBeGreaterThan(10)
    expect(PRODUCTION_TUNING.level.gunkDangerCleanupRelief).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.gunkOvergrowthMassScale).toBeGreaterThan(0.6)
    expect(PRODUCTION_TUNING.level.gunkOvergrowthLinearFillSeconds).toBeGreaterThanOrEqual(18)
    expect(PRODUCTION_TUNING.level.gunkOvergrowthLinearFillSeconds).toBeLessThan(28)
    expect(PRODUCTION_TUNING.level.waveExhaustionFadeSeconds).toBeGreaterThan(4)
    expect(PRODUCTION_TUNING.level.waveClearUnlockExhaustion).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.level.waveClearUnlockExhaustion).toBeLessThan(0.9)
    expect(PRODUCTION_TUNING.level.postWaveGenerationMultiplier).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.postWaveGenerationMultiplier).toBeLessThan(0.12)
    expect(PRODUCTION_TUNING.level.postWaveOvergrowthTarget).toBeGreaterThanOrEqual(0)
    expect(PRODUCTION_TUNING.level.postWaveOvergrowthTarget).toBeLessThan(0.2)
    expect(PRODUCTION_TUNING.level.gunkOvergrowthMinStreamWhileCleaning).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.gunkOvergrowthCleanupDrain).toBeLessThan(0.8)
    expect(PRODUCTION_TUNING.level.gunkTideBaselineMoteRatio).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.level.gunkTideBaselineMoteRatio).toBeLessThan(0.26)
    expect(PRODUCTION_TUNING.level.gunkTideImmediateSproutSeconds).toBeLessThanOrEqual(0.12)
    expect(PRODUCTION_TUNING.level.gunkTideOvergrowthMassGrowth).toBeGreaterThan(1.3)
    expect(PRODUCTION_TUNING.level.gunkTideOvergrowthMassGrowth).toBeLessThan(1.45)
    expect(PRODUCTION_TUNING.level.gunkTideVisibleGrowth).toBeGreaterThan(1.05)
    expect(PRODUCTION_TUNING.level.gunkTideVisibleGrowth).toBeLessThan(1.18)
    expect(PRODUCTION_TUNING.level.gunkTideDefeatMassGrowth).toBeGreaterThan(PRODUCTION_TUNING.level.gunkTideOvergrowthMassGrowth)
    expect(PRODUCTION_TUNING.level.noCollectionGraceSeconds).toBeGreaterThan(4)
    expect(PRODUCTION_TUNING.level.noCollectionGraceSeconds).toBeLessThan(10)
    expect(PRODUCTION_TUNING.level.noCollectionProgressEpsilon).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.noCollectionProgressEpsilon).toBeLessThan(0.05)
    expect(PRODUCTION_TUNING.level.noCollectionMassEpsilon).toBeGreaterThan(0)
    expect(PRODUCTION_TUNING.level.noCollectionMassEpsilon).toBeLessThan(0.05)
    expect(PRODUCTION_TUNING.level.noCollectionRampSeconds).toBeGreaterThan(10)
    expect(PRODUCTION_TUNING.level.noCollectionPressureRise).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.noCollectionPressureFall).toBeGreaterThan(PRODUCTION_TUNING.level.noCollectionPressureRise)
    expect(PRODUCTION_TUNING.level.noCollectionRegenBoost).toBeLessThan(1)
    expect(PRODUCTION_TUNING.level.noCollectionOvertakeBoost).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.level.slowCleanupGraceProgress).toBeGreaterThan(0.05)
    expect(PRODUCTION_TUNING.level.slowCleanupGraceProgress).toBeLessThan(0.4)
    expect(PRODUCTION_TUNING.level.slowCleanupExpectedCurve).toBeGreaterThan(0.5)
    expect(PRODUCTION_TUNING.level.slowCleanupExpectedCurve).toBeLessThan(1.2)
    expect(PRODUCTION_TUNING.level.slowCleanupProgressBuffer).toBeGreaterThan(0.02)
    expect(PRODUCTION_TUNING.level.slowCleanupProgressBuffer).toBeLessThan(0.2)
    expect(PRODUCTION_TUNING.level.slowCleanupPressureRise).toBeGreaterThan(0.8)
    expect(PRODUCTION_TUNING.level.slowCleanupPressureFall).toBeGreaterThan(PRODUCTION_TUNING.level.slowCleanupPressureRise)
    expect(PRODUCTION_TUNING.level.slowCleanupNoCollectionBias).toBeGreaterThan(0.3)
    expect(PRODUCTION_TUNING.level.slowCleanupRegenBoost).toBeGreaterThan(0.2)
    expect(PRODUCTION_TUNING.level.slowCleanupOvertakeBoost).toBeGreaterThan(0.6)
    expect(PRODUCTION_TUNING.level.slowCleanupOvertakeBoost).toBeGreaterThan(PRODUCTION_TUNING.level.noCollectionOvertakeBoost)
    expect(PRODUCTION_TUNING.level.lossFloodStartPressure).toBeGreaterThan(PRODUCTION_TUNING.level.overtakeWarningThreshold)
    expect(PRODUCTION_TUNING.level.lossFloodStartPressure).toBeLessThan(PRODUCTION_TUNING.level.overtakeLossThreshold)
    expect(PRODUCTION_TUNING.level.lossArenaFloodOpacity).toBeGreaterThan(0.75)
    expect(PRODUCTION_TUNING.level.lossArenaFloodOpacity).toBeLessThanOrEqual(1)
    expect(PRODUCTION_TUNING.level.lossArenaFloodScale).toBeGreaterThan(1.2)
    expect(PRODUCTION_TUNING.level.lossVacuumSubmergeStrength).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.level.lossVacuumSubmergeStrength).toBeLessThan(1.2)
    expect(PRODUCTION_TUNING.level.finalCleanupStart).toBeGreaterThan(0.25)
    expect(PRODUCTION_TUNING.level.finalCleanupStart).toBeLessThan(PRODUCTION_TUNING.level.difficulty.easy.cleanupTarget)
    expect(PRODUCTION_TUNING.level.finalCleanupPullRadius).toBeGreaterThan(1)
    expect(PRODUCTION_TUNING.level.difficulty.easy.cleanupTarget).toBeLessThan(PRODUCTION_TUNING.level.difficulty.normal.cleanupTarget)
    expect(PRODUCTION_TUNING.level.difficulty.normal.cleanupTarget).toBeLessThan(PRODUCTION_TUNING.level.difficulty.hard.cleanupTarget)
    expect(PRODUCTION_TUNING.level.difficulty.easy.cleanupTarget).toBeGreaterThan(0.35)
    expect(PRODUCTION_TUNING.level.difficulty.hard.cleanupTarget).toBeGreaterThan(0.65)
    expect(PRODUCTION_TUNING.level.difficulty.easy.regenStartCompletion).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.hard.regenStartCompletion)
    expect(PRODUCTION_TUNING.level.difficulty.hard.reviveCostScale).toBeLessThan(PRODUCTION_TUNING.level.difficulty.normal.reviveCostScale)
    expect(PRODUCTION_TUNING.level.difficulty.normal.reviveCostScale).toBeLessThan(PRODUCTION_TUNING.level.difficulty.easy.reviveCostScale)
    expect(PRODUCTION_TUNING.level.difficulty.easy.regenerationRate).toBeLessThan(PRODUCTION_TUNING.level.difficulty.normal.regenerationRate)
    expect(PRODUCTION_TUNING.level.difficulty.normal.regenerationRate).toBeGreaterThan(0.02)
    expect(PRODUCTION_TUNING.level.difficulty.hard.regenerationRate).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.normal.regenerationRate)
    expect(PRODUCTION_TUNING.level.difficulty.easy.finalCleanupMultiplier).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.hard.finalCleanupMultiplier)
    expect(PRODUCTION_TUNING.level.difficulty.easy.waveTimeLimitSeconds).toBeLessThan(PRODUCTION_TUNING.level.difficulty.normal.waveTimeLimitSeconds)
    expect(PRODUCTION_TUNING.level.difficulty.normal.waveTimeLimitSeconds).toBeLessThan(PRODUCTION_TUNING.level.difficulty.hard.waveTimeLimitSeconds)
    expect(PRODUCTION_TUNING.level.difficulty.easy.overtakeMassStart).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.hard.overtakeMassStart)
    expect(PRODUCTION_TUNING.level.difficulty.hard.overtakePressureScale).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.easy.overtakePressureScale)
    expect(PRODUCTION_TUNING.level.difficulty.easy.noCollectionGraceScale).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.normal.noCollectionGraceScale)
    expect(PRODUCTION_TUNING.level.difficulty.normal.noCollectionGraceScale).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.hard.noCollectionGraceScale)
    expect(PRODUCTION_TUNING.level.difficulty.easy.noCollectionPressureScale).toBeLessThan(PRODUCTION_TUNING.level.difficulty.normal.noCollectionPressureScale)
    expect(PRODUCTION_TUNING.level.difficulty.normal.noCollectionPressureScale).toBeLessThan(PRODUCTION_TUNING.level.difficulty.hard.noCollectionPressureScale)
    expect(PRODUCTION_TUNING.level.difficulty.easy.slowCleanupPressureScale).toBeLessThan(PRODUCTION_TUNING.level.difficulty.normal.slowCleanupPressureScale)
    expect(PRODUCTION_TUNING.level.difficulty.normal.slowCleanupPressureScale).toBeLessThan(PRODUCTION_TUNING.level.difficulty.hard.slowCleanupPressureScale)
    expect(PRODUCTION_TUNING.level.difficulty.easy.slowCleanupBufferScale).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.normal.slowCleanupBufferScale)
    expect(PRODUCTION_TUNING.level.difficulty.normal.slowCleanupBufferScale).toBeGreaterThan(PRODUCTION_TUNING.level.difficulty.hard.slowCleanupBufferScale)
  })

  it('keeps full-loop win and loss finale triggers gated by visible gunk coverage', () => {
    expect(experimentLabSource).toContain('function isVisibleCoverageClear')
    expect(experimentLabSource).toContain('function isVisibleCoverageOvertaken')
    expect(experimentLabSource).toContain('function computeLinearGunkCoverageTarget')
    expect(experimentLabSource).toContain('function applyVisibleGunkTideGrowth')
    expect(experimentLabSource).toContain('function computeTideMoteActivation')
    expect(experimentLabSource).toContain('state.levelRawVisibleMass = rawRemainingMass')
    expect(experimentLabSource).toContain('levelSlimeFloorTakeover')
    expect(experimentLabSource).toContain('const coverage = clampValue(rawCoverage, 0, 1)')
    expect(experimentLabSource).toContain('state.levelGunkOvergrowth >= 1')
    expect(experimentLabSource).toContain('tideVisibleRatio >= 0.985')
    expect(experimentLabSource).toContain('function isWaveExhaustedForClear')
    expect(experimentLabSource).toContain('function computeWaveGenerationMultiplier')
    expect(experimentLabSource).toContain('function canTriggerLevelCompletionFromCoverage')
    expect(experimentLabSource).toContain('if (!options.force && !canTriggerLevelCompletionFromCoverage(state)) return')
    expect(experimentLabSource).toContain('if (!options.force && !isVisibleCoverageOvertaken(state)) return')
    expect(experimentLabSource).toContain('function computeImmediateTideSprout')
    expect(experimentLabSource).toContain('const immediateActivation = immediateSprout * immediateSlotStrength * 0.42')
    expect(experimentLabSource).toContain('const linearOvergrowthClock = clampValue')
    expect(experimentLabSource).toContain('FIRST_LEVEL_TUNING.postWaveOvergrowthTarget * waveExhaustionProgress')
    expect(experimentLabSource).toContain('Math.max(cleanupStreamFloor, 1 - cleanupStreamDrag)')
    expect(experimentLabSource).toContain('levelGunkOvergrowthCleanupCredit')
    expect(experimentLabSource).toContain('const visibleCleanupRegistered = playerCleanupActive')
    expect(experimentLabSource).toContain('const residueAutoCleanupActive = visibleSlimeVacuumability.autoCleanup && !emergingTideMote')
    expect(experimentLabSource).toContain('const regenBankPieceScale = Math.sqrt(motes.length)')
    expect(experimentLabSource).not.toContain('pressureLossReached')
    expect(experimentLabSource).toContain('if (canTriggerLevelCompletionFromCoverage(state)) triggerLevelCompletion(state, now)')
  })

  it('keeps the active full-loop gunk HUD focused on a simple gauge', () => {
    expect(experimentLabSource).toContain('simpleGunkMeterOverlay')
    expect(experimentLabSource).toContain('simpleGunkMeterObject')
    expect(experimentLabSource).toContain('simpleGunkNeedle')
    expect(experimentLabSource).not.toContain('className="levelMeterHeader"')
    expect(experimentLabSource).not.toContain('className="levelGaugeReadout')
    expect(experimentLabSource).not.toContain('className="levelWaveReadout"')
    expect(experimentLabSource).not.toContain('className="levelMeterGreebles"')
    expect(experimentLabSource).not.toContain('className="levelPartySync"')
  })

  it('exposes the organic slime behaviour pass through runtime proof strings and tuning hooks', () => {
    expect(experimentLabSource).toContain("slimeVacuumInteraction: 'organic-slime-suction-bridge-glug-strain-snap-v34'")
    expect(experimentLabSource).toContain("mergeModel: 'organic-reference-soft-congeal-seams-v7'")
    expect(experimentLabSource).toContain("slimeMaterialModel: 'experiment-native-toon-organic-slime-behaviour-v6'")
    expect(experimentLabSource).toContain("slimePhysicsModel: 'viscoelastic-jelly-wax-organic-behaviour-v22'")
    expect(experimentLabSource).toContain('livingTuning.suctionBulgeStrength')
    expect(experimentLabSource).toContain('livingTuning.bridgeOrganicness')
    expect(experimentLabSource).toContain('livingTuning.bridgeTaperStrength')
    expect(experimentLabSource).toContain('livingTuning.depletionCrawlStrength')
    expect(experimentLabSource).toContain('livingTuning.mergeSeamSwirlStrength')
    expect(experimentLabSource).toContain('livingTuning.internalFlowStrength')
    expect(experimentLabSource).toContain('approachBridgeVisual')
    expect(experimentLabSource).toContain('funnelVisualConnected')
    expect(experimentLabSource).toContain('initialBiteDepthN')
    expect(experimentLabSource).toContain('pocketVisualConnected = mouthBridgePhysicallyConnected || stickyAnchorActive')
  })

	  it('exposes all-visible slime vacuumability diagnostics and tiny residue cleanup paths', () => {
    expect(experimentLabSource).toContain('computeVisibleSlimeVacuumability')
    expect(experimentLabSource).toContain('allVisibleSlimeVacuumableModel')
    expect(experimentLabSource).toContain('slimeVacuumableVisibleCount')
    expect(experimentLabSource).toContain('slimeVacuumableTinyCount')
    expect(experimentLabSource).toContain('slimeVacuumableStrandedCount')
    expect(experimentLabSource).toContain('slimeVisualEffectResidueCount')
    expect(experimentLabSource).toContain('visibleResidueSwallowed')
    expect(experimentLabSource).toContain('visibleSlimeSurfaceDistance')
    expect(experimentLabSource).toContain('visibleSlimeBodyPickupRadius')
    expect(experimentLabSource).toContain('visibleSlimeRelativeDrainScale')
    expect(experimentLabSource).toContain('visualSlimeResidueEnabled')
    expect(experimentLabSource).toContain('mote.visibleMass * (1 - visibleSlimeVacuumability.massDrain')
    expect(experimentLabSource).toContain('slimeResidueMouthPopRadius')
    expect(experimentLabSource).toContain('visualSlimeResidueMaxLife')
    expect(experimentLabSource).toContain('function applyContinuousSlimeGeneration')
    expect(experimentLabSource).toContain('function seedContinuousSlimeBud')
    expect(experimentLabSource).toContain('function isBigSlimeColonyMoteIndex')
    expect(experimentLabSource).toContain('return tideSlot % 6 <= 4')
    expect(experimentLabSource).toContain('const satelliteBud = parentColonyStrength > 0.12')
    expect(experimentLabSource).toContain('Math.min(7, Math.floor(state.levelSlimeGenerationBudBudget))')
    expect(experimentLabSource).toContain('const maxVisible = bigColony ? 1.28 : 1.02')
    expect(experimentLabSource).toContain("levelSlimeGenerationModel: PRODUCTION_TUNING.livingSlime.continuousGenerationModel")
    expect(experimentLabSource).toContain("state.levelState === 'ready' || state.levelState === 'playing' || state.levelState === 'nearComplete'")
    expect(experimentLabSource).toContain('mote.growthTarget = Math.min(mote.growthTarget, mote.visibleMass)')
    expect(experimentLabSource).toContain('PRODUCTION_TUNING.suction.slimeVacuumableVisibleThreshold * 4.5')
	    expect(experimentLabSource).toContain('const groupReach = 1.42 + (a.size + b.size) * 4.25')
	  })

	  it('makes visible edge contact eligible for immediate sticky latch across slime sizes', () => {
	    expect(experimentLabSource).toContain("suctionLatchAssistModel: 'all-size-edge-contact-latch-grab-v1'")
	    expect(experimentLabSource).toContain('suctionLatchContactRadius: PRODUCTION_TUNING.suction.physicalContactGraceDistance')
	    expect(experimentLabSource).toContain('suctionLatchSurfaceLockReach: PRODUCTION_TUNING.suction.pileSurfaceLockReach')
	    expect(experimentLabSource).toContain('suctionLatchStickyThreshold: PRODUCTION_TUNING.suction.stickySealStrengthThreshold')
	    expect(experimentLabSource).toContain('visibleFloor: 0.08')
	    expect(experimentLabSource).toContain('|| pileSurfaceAssist.lock > 0.1')
	    expect(experimentLabSource).toContain('|| pileSurfaceAssist.sealBoost > 0.12')
	    expect(experimentLabSource).toContain('pileSurfaceAssist.lock > 0.12')
	    expect(experimentLabSource).toContain('pileSurfaceAssist.sealBoost * 0.32')
	    expect(PRODUCTION_TUNING.suction.stickySealStrengthThreshold).toBeLessThan(0.4)
	    expect(PRODUCTION_TUNING.suction.pileSurfaceLockReach).toBeGreaterThan(PRODUCTION_TUNING.suction.attachmentRadius)
	    expect(PRODUCTION_TUNING.suction.suctionContactMagnetStrength).toBeGreaterThan(10)
	  })

	  it('treats colorful tiny slime as pickupable by visible surface contact', () => {
    const result = computeVisibleSlimeVacuumability({
      distanceToMouth: 1.4,
      surfaceDistanceToMouth: 0.18,
      visibleMass: 0.045,
      mass: 0.12,
      popProgress: 1,
      suctionActive: false,
      latched: false,
      levelCleared: false,
      stuckAge: 0,
    })

    expect(result.visible).toBe(true)
    expect(result.fragment).toBe(true)
    expect(result.mouthPopReady).toBe(true)
    expect(result.mouthPull).toBeGreaterThan(0)
    expect(result.massDrain).toBeGreaterThan(0.5)
  })

  it('gives tiny colorful slime a generous passive suction field', () => {
    const result = computeVisibleSlimeVacuumability({
      distanceToMouth: 2.15,
      surfaceDistanceToMouth: 1.55,
      visibleMass: 0.05,
      mass: 0.14,
      popProgress: 1,
      suctionActive: false,
      latched: false,
      levelCleared: false,
      stuckAge: 0,
    })

    expect(result.visible).toBe(true)
    expect(result.fragment).toBe(true)
    expect(result.mouthPopReady).toBe(true)
    expect(result.mouthPull).toBeGreaterThan(1.2)
    expect(result.feed).toBeGreaterThan(0.18)
  })

  it('keeps the loss finale on actual slime blobs instead of fake floor overlays', () => {
    expect(experimentLabSource).toContain("levelModel: 'linear-battle-slime-tide-v52'")
    expect(experimentLabSource).toContain("defeatFinaleModel: 'ninety-nine-coverage-slime-only-loss-v51'")
    expect(experimentLabSource).toContain('const MOTE_COUNT = 620')
    expect(experimentLabSource).toContain('function resolveTideMoteHome')
    expect(experimentLabSource).toContain('const tideBlobGrowth = isFirstLevelMode(state.devMode)')
    expect(experimentLabSource).toContain('defeatFloodNudge')
    expect(experimentLabSource).not.toContain('const GUNK_TAKEOVER_PATCH_COUNT')
    expect(experimentLabSource).not.toContain('Math.max(0.98, smooth01')
    expect(experimentLabSource).not.toContain('slimeBaseMesh')
    expect(experimentLabSource).not.toContain('slimeAccentMesh')
    expect(experimentLabSource).not.toContain('slimeWarmMesh')
    expect(experimentLabSource).not.toContain('patchPalette')
    expect(experimentLabSource).not.toContain('makeOrganicSlimeSheetGeometry')
    expect(experimentLabSource).not.toContain("color: '#8bf4ff'")
    expect(experimentLabSource).not.toContain("color: '#fff07a'")
    expect(experimentLabSource).not.toContain('GUNK_OVERTAKE_PALETTE')
    expect(experimentLabSource).not.toContain('gunk-overtake-blob')
    expect(experimentLabSource).not.toContain('arenaFlood')
    expect(experimentLabSource).not.toContain('vacuumBlob')
  })

  it('keeps large slime takeover accents rounded and anchored instead of spinning as giant ovals', () => {
    expect(experimentLabSource).toContain('const SLIME_TIDE_MAX_SIZE_SCALE = 0.34')
    expect(experimentLabSource).toContain('const SLIME_TIDE_OVERGROWTH_BLOB_GROWTH = 1.16 * SLIME_TIDE_MAX_SIZE_SCALE')
    expect(experimentLabSource).toContain('const SLIME_TIDE_COVERAGE_SCALE_GAIN = 3.0 * SLIME_TIDE_MAX_SIZE_SCALE')
    expect(experimentLabSource).toContain('const SLIME_ACCENT_TIDE_GROWTH_LIMIT = 0.23')
    expect(experimentLabSource).toContain('const SLIME_ACCENT_MAX_YAW_WOBBLE = 0.055')
    expect(experimentLabSource).toContain('const SLIME_PILE_LOBE_MAX_STRETCH = 1.18')
    expect(experimentLabSource).toContain('const SLIME_BODY_LOBE_MAX_STRETCH = 1.06')
    expect(experimentLabSource).toContain('const SLIME_TIDE_BODY_ROUNDNESS_MAX = 0.78')
    expect(experimentLabSource).toContain('const SLIME_BODY_LOBES_PER_MOTE = 3')
    expect(experimentLabSource).toContain('const tideBodyRoundness = clampValue(')
    expect(experimentLabSource).toContain('const passiveTideYaw = seededNoise(mote.seed + 91.3) * Math.PI * 2')
    expect(experimentLabSource).toContain('const accentTideGrowth = clampValue(tideBlobGrowth, 0, SLIME_ACCENT_TIDE_GROWTH_LIMIT)')
    expect(experimentLabSource).toContain('const baseAngle = seededNoise(pile.seed + lobeIndex * 3.17) * Math.PI * 2')
    expect(experimentLabSource).not.toContain('+ Math.sin(t * 0.28 + lobeIndex) * (0.08 + pile.livingPulse * 0.08)')
    expect(experimentLabSource).not.toContain('* (1 + tideBlobGrowth * 0.82)')
  })
})
