import type { LevelData } from "../levelTypes"
import {
  makeCollisionVolume,
  makeFlatSurface,
  makeRoundTopSurface,
  makeSlopeSurface,
  makeSpawn,
  makeTransition,
  makeWaterZone,
} from "../collisionData"

export const optionDOverworldSeed: LevelData = {
  id: "option-d-overworld",
  displayName: "Option D: The Long Approach",
  kind: "overworld",

  bounds: {
    min: { x: -50, y: -5, z: -25 },
    max: { x: 50, y: 16, z: 150 },
  },

  elevationBands: [
    { id: "river-floor", label: "River floor", y: -2, tolerance: 0.1, gameplayRole: "hazardFloor", debugColor: "#2f6ea8" },
    { id: "spawn-lawn", label: "Spawn lawn", y: 0, tolerance: 0.05, gameplayRole: "safeFlat", debugColor: "#68c46b" },
    { id: "bridge-deck", label: "Bridge deck", y: 0.05, tolerance: 0.05, gameplayRole: "route", debugColor: "#b6814c" },
    { id: "sign-hill", label: "Sign Hill top", y: 2.5, tolerance: 0.08, gameplayRole: "raisedLandmark", debugColor: "#83c96d" },
    { id: "vista-rock", label: "Vista Rock top", y: 3, tolerance: 0.08, gameplayRole: "raisedLandmark", debugColor: "#a7a2a0" },
    { id: "cave-entrance", label: "Cave entrance ledge", y: 6, tolerance: 0.08, gameplayRole: "route", debugColor: "#a68ca6" },
    { id: "upper-cliff-teaser", label: "Upper cliff teaser", y: 8, tolerance: 0.08, gameplayRole: "secretRoute", debugColor: "#d6a74c" },
    { id: "museum-forecourt", label: "Museum forecourt", y: 3, tolerance: 0.05, gameplayRole: "goalPlateau", debugColor: "#c6b28e" },
    { id: "museum-base-pad", label: "Museum base pad", y: 4, tolerance: 0.05, gameplayRole: "goalPlateau", debugColor: "#d3c0a3" },
  ],

  terrainZones: [
    {
      id: "zone-spawn-lawn",
      label: "Spawn Lawn Low Flat Field",
      kind: "flatField",
      bounds: { center: { x: 0, y: 0, z: 0 }, size: { x: 36, y: 1, z: 28 } },
      baseElevation: 0,
      materialId: "grass",
      routeRole: "start",
      connectsTo: ["zone-long-lawn-path"],
      debug: { color: "#55cc66", validateHasWalkableSurface: true, notes: "Safe onboarding field." },
    },
    {
      id: "zone-long-lawn-path",
      label: "Long Lawn Broad Path",
      kind: "broadPath",
      bounds: { center: { x: 0, y: 0.1, z: 52 }, size: { x: 30, y: 1, z: 90 } },
      baseElevation: 0,
      materialId: "pathDirt",
      routeRole: "mainRoute",
      connectsTo: ["zone-cave-cliff", "zone-vista-rock", "zone-sign-hill", "zone-river-channel", "zone-museum-forecourt"],
      debug: { color: "#d9a84f", validateHasWalkableSurface: true, notes: "Primary route spine. Later replaced by generated path strips." },
    },
    {
      id: "zone-cave-cliff",
      label: "Cave Cliff High Vertical Mass",
      kind: "cliffMass",
      bounds: { center: { x: -29, y: 4, z: 58 }, size: { x: 26, y: 9, z: 36 } },
      baseElevation: 0,
      visualHeight: 8,
      materialId: "cliffRock",
      routeRole: "branchRoute",
      connectsTo: ["zone-cave-entrance-ledge", "zone-upper-cliff-teaser"],
      debug: { color: "#5b5365", validateHasBlockingVolume: true, notes: "Only authored ledges are standable." },
    },
    {
      id: "zone-cave-entrance-ledge",
      label: "Cave Entrance Ledge",
      kind: "ledgeShelf",
      bounds: { center: { x: -29, y: 6, z: 67 }, size: { x: 10, y: 1, z: 8 } },
      baseElevation: 6,
      materialId: "cliffRock",
      routeRole: "branchRoute",
      connectsTo: ["zone-cave-cliff"],
      debug: { color: "#a68ca6", validateHasWalkableSurface: true, notes: "Transition trigger lives inside cave mouth, not across the whole ledge." },
    },
    {
      id: "zone-upper-cliff-teaser",
      label: "Optional Upper Cave Summit Teaser",
      kind: "ledgeShelf",
      bounds: { center: { x: -31, y: 8, z: 75 }, size: { x: 12, y: 1, z: 10 } },
      baseElevation: 8,
      materialId: "cliffRock",
      routeRole: "secret",
      connectsTo: ["zone-cave-cliff"],
      debug: { color: "#d6a74c", validateHasWalkableSurface: true, notes: "May be unreachable in early packages unless a secret route is implemented." },
    },
    {
      id: "zone-vista-rock",
      label: "Vista Rock Mound",
      kind: "mound",
      bounds: { center: { x: 24, y: 1.5, z: 55 }, size: { x: 16, y: 4, z: 16 } },
      baseElevation: 3,
      materialId: "cliffRock",
      routeRole: "landmark",
      connectsTo: ["zone-long-lawn-path"],
      debug: { color: "#a7a2a0", validateHasWalkableSurface: true, validateHasBlockingVolume: true, notes: "Optional view-back landmark." },
    },
    {
      id: "zone-sign-hill",
      label: "Sign Hill Mound",
      kind: "mound",
      bounds: { center: { x: 18, y: 1.25, z: 35 }, size: { x: 14, y: 3.5, z: 14 } },
      baseElevation: 2.5,
      materialId: "grass",
      routeRole: "landmark",
      connectsTo: ["zone-long-lawn-path"],
      debug: { color: "#83c96d", validateHasWalkableSurface: true, notes: "Tutorial/lore sign area." },
    },
    {
      id: "zone-river-channel",
      label: "River and Water Channel",
      kind: "riverChannel",
      bounds: { center: { x: 0, y: -1.2, z: 88 }, size: { x: 84, y: 3, z: 14 } },
      baseElevation: -2,
      materialId: "water",
      routeRole: "hazard",
      connectsTo: ["zone-bridge-crossing", "zone-stepping-stone-pocket", "zone-museum-forecourt"],
      debug: { color: "#3a8dff", validateHasBlockingVolume: true, notes: "Water reset zone and river bank blockers." },
    },
    {
      id: "zone-bridge-crossing",
      label: "Bridge Crossing",
      kind: "bridge",
      bounds: { center: { x: -4, y: 0.05, z: 88 }, size: { x: 5, y: 0.2, z: 18 } },
      baseElevation: 0.05,
      materialId: "wood",
      routeRole: "mainRoute",
      connectsTo: ["zone-long-lawn-path", "zone-museum-forecourt"],
      debug: { color: "#b6814c", validateHasWalkableSurface: true, validateHasBlockingVolume: true, notes: "Safe primary water crossing." },
    },
    {
      id: "zone-stepping-stone-pocket",
      label: "Stepping Stone Pocket",
      kind: "steppingStonePocket",
      bounds: { center: { x: 18, y: 0.2, z: 90 }, size: { x: 14, y: 1.5, z: 10 } },
      baseElevation: 0.25,
      materialId: "cliffRock",
      routeRole: "branchRoute",
      connectsTo: ["zone-long-lawn-path", "zone-museum-forecourt"],
      debug: { color: "#b7a089", validateHasWalkableSurface: true, notes: "Optional skill crossing." },
    },
    {
      id: "zone-museum-forecourt",
      label: "Museum Forecourt Plateau",
      kind: "forecourt",
      bounds: { center: { x: 0, y: 3, z: 118 }, size: { x: 42, y: 1, z: 30 } },
      baseElevation: 3,
      materialId: "museumStone",
      routeRole: "goal",
      connectsTo: ["zone-museum-base-pad", "zone-bridge-crossing", "zone-stepping-stone-pocket"],
      debug: { color: "#c6b28e", validateHasWalkableSurface: true, notes: "Goal plateau and museum reveal area." },
    },
    {
      id: "zone-museum-base-pad",
      label: "Museum Base Pad",
      kind: "museumBase",
      bounds: { center: { x: 0, y: 4, z: 134 }, size: { x: 22, y: 1, z: 10 } },
      baseElevation: 4,
      materialId: "museumStone",
      routeRole: "goal",
      connectsTo: ["zone-museum-door-seal", "zone-museum-forecourt"],
      debug: { color: "#d3c0a3", validateHasWalkableSurface: true, notes: "Raised pad directly in front of locked seal." },
    },
    {
      id: "zone-museum-door-seal",
      label: "Locked Museum Door and Seal",
      kind: "doorSeal",
      bounds: { center: { x: 0, y: 5, z: 141 }, size: { x: 18, y: 8, z: 2 } },
      baseElevation: 4,
      visualHeight: 9,
      materialId: "sealMagic",
      routeRole: "goal",
      connectsTo: ["zone-museum-base-pad"],
      debug: { color: "#d665ff", validateHasBlockingVolume: true, notes: "Door cannot be bypassed in first shell." },
    },
  ],

  walkableSurfaces: [
    makeFlatSurface({ id: "surface-spawn-lawn", label: "Spawn Lawn Surface", zoneId: "zone-spawn-lawn", center: { x: 0, y: 0, z: 0 }, size: { x: 36, y: 0.1, z: 28 }, surfaceTags: ["ground", "grass"], color: "#55cc66" }),
    makeFlatSurface({ id: "surface-long-lawn-placeholder", label: "Long Lawn Placeholder Surface", zoneId: "zone-long-lawn-path", center: { x: 0, y: 0.02, z: 32 }, size: { x: 24, y: 0.1, z: 80 }, surfaceTags: ["ground", "path"], color: "#d9a84f" }),
    makeFlatSurface({ id: "surface-cave-low-ledge", label: "Cave Low Ledge", zoneId: "zone-cave-cliff", center: { x: -22, y: 2, z: 54 }, size: { x: 8, y: 0.1, z: 5 }, yawRadians: 0.2, surfaceTags: ["ground", "ledge", "stone"], color: "#9c8f86" }),
    makeFlatSurface({ id: "surface-cave-mid-ledge", label: "Cave Mid Ledge", zoneId: "zone-cave-cliff", center: { x: -27, y: 4, z: 60 }, size: { x: 7, y: 0.1, z: 5 }, yawRadians: -0.1, surfaceTags: ["ground", "ledge", "stone"], color: "#9c8f86" }),
    makeFlatSurface({ id: "surface-cave-entrance-ledge", label: "Cave Entrance Ledge", zoneId: "zone-cave-entrance-ledge", center: { x: -29, y: 6, z: 67 }, size: { x: 10, y: 0.1, z: 8 }, surfaceTags: ["ground", "ledge", "stone"], color: "#b7a089" }),
    makeFlatSurface({ id: "surface-upper-cliff-teaser", label: "Upper Cliff Teaser Shelf", zoneId: "zone-upper-cliff-teaser", center: { x: -31, y: 8, z: 75 }, size: { x: 12, y: 0.1, z: 10 }, surfaceTags: ["ground", "secret", "stone"], color: "#d6a74c" }),
    makeFlatSurface({ id: "surface-vista-rock-top", label: "Vista Rock Top", zoneId: "zone-vista-rock", center: { x: 24, y: 3, z: 55 }, size: { x: 9, y: 0.1, z: 9 }, surfaceTags: ["ground", "stone"], color: "#a7a2a0" }),
    makeFlatSurface({ id: "surface-sign-hill-top", label: "Sign Hill Top", zoneId: "zone-sign-hill", center: { x: 18, y: 2.5, z: 35 }, size: { x: 8, y: 0.1, z: 8 }, surfaceTags: ["ground", "grass"], color: "#83c96d" }),
    makeFlatSurface({ id: "surface-bridge-deck", label: "Bridge Deck", zoneId: "zone-bridge-crossing", center: { x: -4, y: 0.05, z: 88 }, size: { x: 5, y: 0.1, z: 18 }, surfaceTags: ["ground", "bridge"], color: "#b6814c" }),
    makeRoundTopSurface({ id: "surface-step-stone-a", label: "Stepping Stone A", zoneId: "zone-stepping-stone-pocket", center: { x: 13, y: 0.2, z: 86 }, radius: 2.1, surfaceTags: ["ground", "steppingStone"], color: "#b7a089" }),
    makeRoundTopSurface({ id: "surface-step-stone-b", label: "Stepping Stone B", zoneId: "zone-stepping-stone-pocket", center: { x: 18, y: 0.35, z: 90 }, radius: 2.0, surfaceTags: ["ground", "steppingStone"], color: "#b7a089" }),
    makeRoundTopSurface({ id: "surface-step-stone-c", label: "Stepping Stone C", zoneId: "zone-stepping-stone-pocket", center: { x: 23, y: 0.45, z: 94 }, radius: 2.2, surfaceTags: ["ground", "steppingStone"], color: "#b7a089" }),
    makeFlatSurface({ id: "surface-museum-forecourt", label: "Museum Forecourt", zoneId: "zone-museum-forecourt", center: { x: 0, y: 3, z: 129.5 }, size: { x: 42, y: 0.1, z: 7 }, surfaceTags: ["ground", "museum"], color: "#c6b28e" }),
    makeFlatSurface({ id: "surface-museum-base-pad", label: "Museum Base Pad", zoneId: "zone-museum-base-pad", center: { x: 0, y: 4, z: 136.5 }, size: { x: 22, y: 0.1, z: 5 }, surfaceTags: ["ground", "museum"], color: "#d3c0a3" }),
  ],

  collisionVolumes: [
    makeCollisionVolume({ id: "volume-cave-cliff-back-wall", label: "Cave Cliff Back Wall", kind: "aabb", zoneId: "zone-cave-cliff", center: { x: -39, y: 4, z: 59 }, size: { x: 8, y: 9, z: 34 }, collisionTags: ["cliffWall"], color: "#5b5365" }),
    makeCollisionVolume({ id: "volume-cave-cliff-south-buttress", label: "Cave Cliff South Buttress", kind: "aabb", zoneId: "zone-cave-cliff", center: { x: -29, y: 4, z: 42 }, size: { x: 24, y: 9, z: 5 }, collisionTags: ["cliffWall"], color: "#5b5365" }),
    makeCollisionVolume({ id: "volume-cave-cliff-north-buttress", label: "Cave Cliff North Buttress", kind: "aabb", zoneId: "zone-cave-cliff", center: { x: -29, y: 4, z: 78 }, size: { x: 24, y: 9, z: 5 }, collisionTags: ["cliffWall"], color: "#5b5365" }),
    makeCollisionVolume({ id: "volume-vista-rock-sides", label: "Vista Rock Side Blocker", kind: "cylinder", zoneId: "zone-vista-rock", center: { x: 24, y: 1.15, z: 55 }, radius: 8, height: 2.3, collisionTags: ["terrainWall"], response: "softPush", color: "#a7a2a0" }),
    makeCollisionVolume({ id: "volume-river-north-bank-west", label: "River North Bank West", kind: "wall", zoneId: "zone-river-channel", center: { x: -29, y: 0, z: 96 }, size: { x: 26, y: 2, z: 1 }, collisionTags: ["waterBoundary"], response: "softPush", color: "#3a8dff" }),
    makeCollisionVolume({ id: "volume-river-north-bank-east", label: "River North Bank East", kind: "wall", zoneId: "zone-river-channel", center: { x: 38, y: 0, z: 96 }, size: { x: 20, y: 2, z: 1 }, collisionTags: ["waterBoundary"], response: "softPush", color: "#3a8dff" }),
    makeCollisionVolume({ id: "volume-river-south-bank-west", label: "River South Bank West", kind: "wall", zoneId: "zone-river-channel", center: { x: -29, y: 0, z: 80 }, size: { x: 26, y: 2, z: 1 }, collisionTags: ["waterBoundary"], response: "softPush", color: "#3a8dff" }),
    makeCollisionVolume({ id: "volume-river-south-bank-east", label: "River South Bank East", kind: "wall", zoneId: "zone-river-channel", center: { x: 38, y: 0, z: 80 }, size: { x: 20, y: 2, z: 1 }, collisionTags: ["waterBoundary"], response: "softPush", color: "#3a8dff" }),
    makeCollisionVolume({ id: "volume-bridge-left-rail", label: "Bridge Left Rail", kind: "rail", zoneId: "zone-bridge-crossing", center: { x: -6.65, y: 0.7, z: 88 }, size: { x: 0.35, y: 1.2, z: 18 }, collisionTags: ["bridgeRail"], color: "#b6814c" }),
    makeCollisionVolume({ id: "volume-bridge-right-rail", label: "Bridge Right Rail", kind: "rail", zoneId: "zone-bridge-crossing", center: { x: -1.35, y: 0.7, z: 88 }, size: { x: 0.35, y: 1.2, z: 18 }, collisionTags: ["bridgeRail"], color: "#b6814c" }),
    makeCollisionVolume({ id: "volume-museum-door-blocker", label: "Museum Door Blocker", kind: "doorBlocker", zoneId: "zone-museum-door-seal", center: { x: 0, y: 5, z: 140.5 }, size: { x: 18, y: 7, z: 2 }, collisionTags: ["door", "museumWall"], color: "#d665ff", visibleByDefault: true }),
  ],

  slopes: [
    makeSlopeSurface({ id: "slope-main-path-to-bridge", label: "Main Path Rising to Bridge", zoneId: "zone-long-lawn-path", start: { x: -4, y: 0.02, z: 68 }, end: { x: -4, y: 0.05, z: 85.5 }, width: 16, slopeDegrees: 0.1, connectFromSurfaceId: "surface-long-lawn-placeholder", connectToSurfaceId: "surface-bridge-deck", materialId: "pathDirt" }),
    makeSlopeSurface({ id: "slope-main-path-to-forecourt", label: "Main Path Rising to Forecourt", zoneId: "zone-long-lawn-path", start: { x: -4, y: 0.05, z: 90.5 }, end: { x: 0, y: 3, z: 126 }, width: 16, slopeDegrees: 4.8, connectFromSurfaceId: "surface-bridge-deck", connectToSurfaceId: "surface-museum-forecourt", materialId: "pathDirt" }),
    makeSlopeSurface({ id: "slope-stepping-stones-to-forecourt", label: "Stepping Stone Pocket Climb to Forecourt", zoneId: "zone-stepping-stone-pocket", start: { x: 23, y: 0.45, z: 94 }, end: { x: 17, y: 3, z: 104 }, width: 6, slopeDegrees: 13.9, connectFromSurfaceId: "surface-step-stone-c", connectToSurfaceId: "surface-museum-forecourt", materialId: "cliffPath" }),
    makeSlopeSurface({ id: "slope-forecourt-to-museum-base-pad", label: "Forecourt Rise to Museum Base Pad", zoneId: "zone-museum-base-pad", start: { x: 0, y: 2.2, z: 116 }, end: { x: 0, y: 4, z: 134 }, width: 20, slopeDegrees: 5.7, connectFromSurfaceId: "surface-museum-forecourt", connectToSurfaceId: "surface-museum-base-pad", materialId: "museumStone" }),
  ],

  climbSurfaces: [
    { id: "climb-cave-low-ledge", label: "Cave Low Ledge Climb Step", zoneId: "zone-cave-cliff", kind: "stoneShelf", center: { x: -22, y: 2, z: 54 }, size: { x: 8, y: 0.4, z: 5 }, topY: 2, requiredJumpHeight: 2.1, connectsFrom: ["zone-long-lawn-path"], connectsTo: ["surface-cave-low-ledge"], assist: "smallCoyoteTime", debug: { color: "#9c8f86", showRouteIndex: 1 } },
    { id: "climb-cave-mid-ledge", label: "Cave Mid Ledge Climb Step", zoneId: "zone-cave-cliff", kind: "stoneShelf", center: { x: -27, y: 4, z: 60 }, size: { x: 7, y: 0.4, z: 5 }, topY: 4, requiredJumpHeight: 2.1, connectsFrom: ["surface-cave-low-ledge"], connectsTo: ["surface-cave-mid-ledge"], assist: "smallCoyoteTime", debug: { color: "#9c8f86", showRouteIndex: 2 } },
    { id: "climb-cave-entrance-ledge", label: "Cave Entrance Final Climb Step", zoneId: "zone-cave-entrance-ledge", kind: "rootStep", center: { x: -29, y: 6, z: 67 }, size: { x: 10, y: 0.4, z: 8 }, topY: 6, requiredJumpHeight: 2.2, connectsFrom: ["surface-cave-mid-ledge"], connectsTo: ["surface-cave-entrance-ledge"], assist: "ledgeForgiveness", debug: { color: "#b7a089", showRouteIndex: 3 } },
  ],

  ledges: [
    { id: "ledge-forecourt-front", label: "Forecourt Front Drop", zoneId: "zone-museum-forecourt", edgeStart: { x: -21, y: 3, z: 103 }, edgeEnd: { x: 21, y: 3, z: 103 }, topSurfaceId: "surface-museum-forecourt", dropHeight: 2.5, behavior: "fallAllowed", debug: { color: "#c6b28e", validateDropHeight: true } },
    { id: "ledge-cave-entrance-front", label: "Cave Entrance Front Drop", zoneId: "zone-cave-entrance-ledge", edgeStart: { x: -34, y: 6, z: 63 }, edgeEnd: { x: -24, y: 6, z: 63 }, topSurfaceId: "surface-cave-entrance-ledge", dropHeight: 4, behavior: "fallAllowed", debug: { color: "#b7a089", validateDropHeight: true } },
  ],

  waterZones: [
    makeWaterZone({ id: "water-river-channel", label: "River Reset Water", bounds: { center: { x: 0, y: -1.1, z: 88 }, size: { x: 84, y: 2.4, z: 14 } }, waterSurfaceY: -1.1, floorY: -2, resetSpawnId: "spawn-pre-river-reset" }),
  ],

  paths: [
    {
      id: "path-main-long-lawn",
      label: "Main Long Lawn Path",
      levelId: "option-d-overworld",
      kind: "mainPath",
      points: [
        { x: 0, y: 0.02, z: -6 },
        { x: 1, y: 0.02, z: 16 },
        { x: -2, y: 0.05, z: 42 },
        { x: 2, y: 0.15, z: 70 },
        { x: -4, y: 0.05, z: 88 },
        { x: 0, y: 3, z: 112 },
      ],
      width: { default: 9, samples: [{ t: 0, width: 11 }, { t: 0.4, width: 10 }, { t: 0.75, width: 8 }, { t: 1, width: 14 }] },
      elevationMode: "usePointY",
      materialId: "pathDirt",
      generated: { createVisualRibbon: true, createCollisionStrip: true, createBeveledEdges: true, createCoinTrail: true, createScatterAvoidance: true },
      route: { fromZoneId: "zone-spawn-lawn", toZoneId: "zone-museum-forecourt", importance: "critical" },
      debug: { color: "#f0c15d", showSpline: true, showSamples: true },
    },
    {
      id: "path-branch-cave-cliff",
      label: "Branch to Cave Cliff",
      levelId: "option-d-overworld",
      kind: "branchPath",
      points: [
        { x: -3, y: 0.05, z: 40 },
        { x: -14, y: 0.2, z: 48 },
        { x: -22, y: 2, z: 54 },
        { x: -27, y: 4, z: 60 },
        { x: -29, y: 6, z: 67 },
      ],
      width: { default: 5 },
      elevationMode: "usePointY",
      materialId: "cliffPath",
      generated: { createVisualRibbon: true, createCollisionStrip: false, createBeveledEdges: false, createCoinTrail: false, createScatterAvoidance: true },
      route: { fromZoneId: "zone-long-lawn-path", toZoneId: "zone-cave-entrance-ledge", branchOfPathId: "path-main-long-lawn", importance: "optional" },
      debug: { color: "#a88c64", showSpline: true, showSamples: true },
    },
    {
      id: "path-branch-vista-rock",
      label: "Branch to Vista Rock",
      levelId: "option-d-overworld",
      kind: "branchPath",
      points: [{ x: 3, y: 0.05, z: 48 }, { x: 14, y: 1.2, z: 52 }, { x: 24, y: 3, z: 55 }],
      width: { default: 4.5 },
      elevationMode: "usePointY",
      materialId: "pathDirt",
      generated: { createVisualRibbon: true, createCollisionStrip: false, createBeveledEdges: false, createCoinTrail: true, createScatterAvoidance: true },
      route: { fromZoneId: "zone-long-lawn-path", toZoneId: "zone-vista-rock", branchOfPathId: "path-main-long-lawn", importance: "optional" },
      debug: { color: "#a7a2a0", showSpline: true, showSamples: true },
    },
    {
      id: "path-branch-sign-hill",
      label: "Branch to Sign Hill",
      levelId: "option-d-overworld",
      kind: "branchPath",
      points: [{ x: 2, y: 0.05, z: 28 }, { x: 11, y: 1.1, z: 32 }, { x: 18, y: 2.5, z: 35 }],
      width: { default: 4.5 },
      elevationMode: "usePointY",
      materialId: "pathDirt",
      generated: { createVisualRibbon: true, createCollisionStrip: false, createBeveledEdges: false, createCoinTrail: false, createScatterAvoidance: true },
      route: { fromZoneId: "zone-long-lawn-path", toZoneId: "zone-sign-hill", branchOfPathId: "path-main-long-lawn", importance: "optional" },
      debug: { color: "#83c96d", showSpline: true, showSamples: true },
    },
  ],

  worldTransitions: [
    makeTransition({ id: "transition-overworld-to-cave", label: "Enter Glowbud Wizard Cave", kind: "caveEntrance", fromLevelId: "option-d-overworld", toLevelId: "glowbud-wizard-cave", targetSpawnId: "spawn-cave-entry", bounds: { center: { x: -29, y: 6.8, z: 70 }, size: { x: 12, y: 4, z: 7 } }, requireButtonPress: true, promptText: "Enter Cave" }),
    makeTransition({ id: "transition-door-seal-attempt", label: "Locked Museum Seal Attempt", kind: "doorAttempt", fromLevelId: "option-d-overworld", toLevelId: "option-d-overworld", targetSpawnId: "spawn-museum-door", bounds: { center: { x: 0, y: 4.7, z: 137.5 }, size: { x: 10, y: 3, z: 3 } }, requireButtonPress: true, promptText: "Seal locked. Ask the Glowbud Wizard.", style: "instant", color: "#d665ff" }),
  ],

  spawnPoints: [
    makeSpawn({ id: "spawn-initial", label: "Initial Spawn", levelId: "option-d-overworld", position: { x: 0, y: 0.6, z: -8 }, kind: "initial", cameraZoneHint: "camera-zone-default" }),
    makeSpawn({ id: "spawn-pre-river-reset", label: "Pre River Reset", levelId: "option-d-overworld", position: { x: -6, y: 0.8, z: 76 }, kind: "waterReset", cameraZoneHint: "camera-zone-water-crossing", color: "#3a8dff" }),
    makeSpawn({ id: "spawn-return-from-cave", label: "Return From Cave", levelId: "option-d-overworld", position: { x: -29, y: 6.6, z: 64 }, yawRadians: 3.14, kind: "returnFromCave", cameraZoneHint: "camera-zone-cave-climb", color: "#8a5cff" }),
    makeSpawn({ id: "spawn-museum-door", label: "Museum Door Debug Spawn", levelId: "option-d-overworld", position: { x: 0, y: 4.6, z: 132 }, kind: "debug", cameraZoneHint: "camera-zone-door-seal", color: "#d665ff" }),
  ],

  cameraZones: [
    { id: "camera-zone-default", label: "Default Follow Camera", bounds: { center: { x: 0, y: 3, z: 35 }, size: { x: 90, y: 20, z: 90 } }, priority: 1, mode: "defaultFollow", camera: { targetOffset: { x: 0, y: 1.2, z: 0 }, cameraOffset: { x: 0, y: 7, z: -12 }, fovDegrees: 50, followLerp: 0.12, lookLerp: 0.16 }, debug: { color: "#ffffff", showBounds: true } },
    { id: "camera-zone-long-approach", label: "Long Approach Camera", bounds: { center: { x: 0, y: 3, z: 62 }, size: { x: 50, y: 18, z: 70 } }, priority: 5, mode: "longApproach", camera: { targetOffset: { x: 0, y: 1.2, z: 3 }, cameraOffset: { x: 0, y: 8, z: -16 }, fovDegrees: 48, followLerp: 0.1, lookLerp: 0.14 }, debug: { color: "#f0c15d", showBounds: true } },
    { id: "camera-zone-cave-climb", label: "Cave Cliff Climb Camera", bounds: { center: { x: -26, y: 4, z: 61 }, size: { x: 26, y: 12, z: 34 } }, priority: 20, mode: "cliffClimb", camera: { targetOffset: { x: 0, y: 1.2, z: 0 }, cameraOffset: { x: 8, y: 7, z: -12 }, fovDegrees: 48, followLerp: 0.12, lookLerp: 0.16 }, constraints: { preventWallClip: true }, debug: { color: "#a06cff", showBounds: true } },
    { id: "camera-zone-water-crossing", label: "Water Crossing Camera", bounds: { center: { x: 0, y: 2, z: 88 }, size: { x: 84, y: 12, z: 24 } }, priority: 12, mode: "waterCrossing", camera: { targetOffset: { x: 0, y: 1, z: 0 }, cameraOffset: { x: 0, y: 9, z: -13 }, fovDegrees: 50, followLerp: 0.11, lookLerp: 0.15 }, debug: { color: "#3a8dff", showBounds: true } },
    { id: "camera-zone-museum-reveal", label: "Museum Reveal Camera", bounds: { center: { x: 0, y: 4, z: 118 }, size: { x: 46, y: 12, z: 30 } }, priority: 15, mode: "museumReveal", camera: { targetOffset: { x: 0, y: 2, z: 8 }, cameraOffset: { x: 0, y: 10, z: -18 }, fovDegrees: 46, followLerp: 0.08, lookLerp: 0.12 }, debug: { color: "#c6b28e", showBounds: true } },
    { id: "camera-zone-door-seal", label: "Door Seal Camera", bounds: { center: { x: 0, y: 5, z: 134 }, size: { x: 24, y: 10, z: 16 } }, priority: 25, mode: "doorSeal", camera: { targetOffset: { x: 0, y: 2.5, z: 3 }, cameraOffset: { x: 0, y: 6, z: -10 }, fovDegrees: 42, followLerp: 0.08, lookLerp: 0.1 }, debug: { color: "#d665ff", showBounds: true } },
  ],

  collectibles: [
    { id: "coin-spawn-lawn-01", label: "Spawn Lawn Coin 01", levelId: "option-d-overworld", kind: "coin", position: { x: 0, y: 1.05, z: 5 }, routeHint: "path-main-long-lawn", respawn: "never", value: 1, debug: { color: "#ffd84a", group: "main-route" } },
    { id: "coin-spawn-lawn-02", label: "Spawn Lawn Coin 02", levelId: "option-d-overworld", kind: "coin", position: { x: -2, y: 1.05, z: 18 }, routeHint: "path-main-long-lawn", respawn: "never", value: 1, debug: { color: "#ffd84a", group: "main-route" } },
    { id: "coin-long-approach-01", label: "Long Approach Coin 01", levelId: "option-d-overworld", kind: "coin", position: { x: 4, y: 1.1, z: 42 }, routeHint: "path-main-long-lawn", respawn: "never", value: 1, debug: { color: "#ffd84a", group: "main-route" } },
    { id: "coin-cave-branch-01", label: "Cave Branch Coin 01", levelId: "option-d-overworld", kind: "coin", position: { x: -18, y: 2.8, z: 54 }, routeHint: "path-branch-cave-cliff", respawn: "never", value: 1, debug: { color: "#ffd84a", group: "cave-branch" } },
    { id: "coin-cave-branch-02", label: "Cave Branch Coin 02", levelId: "option-d-overworld", kind: "coin", position: { x: -27, y: 4.8, z: 62 }, routeHint: "path-branch-cave-cliff", respawn: "never", value: 1, debug: { color: "#ffd84a", group: "cave-branch" } },
    { id: "coin-water-crossing-01", label: "Water Crossing Coin 01", levelId: "option-d-overworld", kind: "largeCoin", position: { x: -3, y: 1.1, z: 92 }, routeHint: "path-main-long-lawn", respawn: "never", value: 3, debug: { color: "#ffef8a", group: "main-route" } },
    { id: "coin-museum-forecourt-01", label: "Museum Forecourt Coin 01", levelId: "option-d-overworld", kind: "coin", position: { x: 4, y: 5.1, z: 122 }, routeHint: "path-main-long-lawn", respawn: "never", value: 1, debug: { color: "#ffd84a", group: "museum" } },
  ],

  questItems: [
    { id: "quest-item-wizard-blessing", label: "Wizard Blessing", levelId: "option-d-overworld", kind: "wizardBlessing", source: "npcReward", grantsQuestFlag: "metGlowbudWizard", debug: { color: "#9aff8a" } },
  ],

  npcs: [],

  signs: [
    { id: "sign-sign-hill-route", label: "Sign Hill Route Sign", levelId: "option-d-overworld", position: { x: 18, y: 3.1, z: 34 }, yawRadians: 3.14, textId: "sign-route-preview", signKind: "directional", pointsToward: "zone-museum-door-seal", debug: { color: "#83c96d" } },
    { id: "sign-museum-seal", label: "Museum Seal Sign", levelId: "option-d-overworld", position: { x: -5.5, y: 4.7, z: 132 }, yawRadians: 0.35, textId: "sign-museum-seal", signKind: "lore", pointsToward: "zone-museum-door-seal", debug: { color: "#d665ff" } },
  ],

  landmarks: [
    { id: "landmark-cave-entrance", label: "Cave Entrance", levelId: "option-d-overworld", kind: "caveEntrance", position: { x: -29, y: 7, z: 70 }, silhouetteRadius: 6, visibleFromZoneIds: ["zone-long-lawn-path", "zone-sign-hill"], debug: { color: "#8a5cff", validateLineOfSight: true } },
    { id: "landmark-vista-rock", label: "Vista Rock", levelId: "option-d-overworld", kind: "vistaRock", position: { x: 24, y: 3, z: 55 }, silhouetteRadius: 7, visibleFromZoneIds: ["zone-long-lawn-path"], debug: { color: "#a7a2a0" } },
    { id: "landmark-sign-hill", label: "Sign Hill", levelId: "option-d-overworld", kind: "signHill", position: { x: 18, y: 2.5, z: 35 }, silhouetteRadius: 6, visibleFromZoneIds: ["zone-spawn-lawn", "zone-long-lawn-path"], debug: { color: "#83c96d" } },
    { id: "landmark-bridge", label: "Bridge Crossing", levelId: "option-d-overworld", kind: "bridge", position: { x: -4, y: 0.05, z: 88 }, silhouetteRadius: 8, visibleFromZoneIds: ["zone-long-lawn-path", "zone-museum-forecourt"], debug: { color: "#b6814c" } },
    { id: "landmark-museum-door", label: "Museum Door", levelId: "option-d-overworld", kind: "museumDoor", position: { x: 0, y: 5, z: 141 }, silhouetteRadius: 12, visibleFromZoneIds: ["zone-long-lawn-path", "zone-museum-forecourt", "zone-vista-rock"], debug: { color: "#d665ff", validateLineOfSight: true } },
  ],

  scatterZones: [
    { id: "scatter-spawn-grass", label: "Spawn Lawn Grass Scatter", levelId: "option-d-overworld", bounds: { center: { x: 0, y: 0, z: 0 }, size: { x: 34, y: 1, z: 26 } }, surfaceY: 0, avoidPathIds: ["path-main-long-lawn"], scatterType: "grassTufts", density: 0.25, seed: 101, placementRules: { minDistanceFromPlayerRoute: 2, minDistanceBetweenInstances: 1.2, maxInstances: 80, alignToSurfaceNormal: true, randomYaw: true, randomScaleRange: [0.8, 1.25] }, debug: { color: "#55cc66", showCandidates: false } },
    { id: "scatter-cave-rocks", label: "Cave Cliff Rock Scatter", levelId: "option-d-overworld", bounds: { center: { x: -29, y: 1, z: 58 }, size: { x: 24, y: 3, z: 34 } }, surfaceY: 0, avoidPathIds: ["path-branch-cave-cliff"], scatterType: "smallRocks", density: 0.18, seed: 202, placementRules: { minDistanceFromPlayerRoute: 2, minDistanceBetweenInstances: 1.5, maxInstances: 50, alignToSurfaceNormal: true, randomYaw: true, randomScaleRange: [0.6, 1.4] }, debug: { color: "#5b5365", showCandidates: false } },
    { id: "scatter-sign-hill-flowers", label: "Sign Hill Flower Scatter", levelId: "option-d-overworld", bounds: { center: { x: 17, y: 2.2, z: 35 }, size: { x: 20, y: 2, z: 20 } }, surfaceY: 2.1, avoidPathIds: ["path-main-long-lawn"], scatterType: "flowers", density: 0.12, seed: 303, placementRules: { minDistanceFromPlayerRoute: 2.5, minDistanceBetweenInstances: 1.1, maxInstances: 30, alignToSurfaceNormal: true, randomYaw: true, randomScaleRange: [0.7, 1.15] }, debug: { color: "#ffcf5a", showCandidates: false } },
  ],

  debug: {
    authoringVersion: 1,
    requiredValidation: {
      requireWalkableForTerrainZones: true,
      requireColliderForSolidVisualZones: true,
      requireSpawnInsideWalkableSurface: true,
      requireCameraZoneCoverage: true,
      requireTransitionTargets: true,
    },
    debugToggles: {
      showTerrainZones: true,
      showWalkableSurfaces: true,
      showCollisionVolumes: true,
      showTriggers: true,
      showPathSplines: true,
      showCameraZones: true,
      showScatterZones: false,
    },
    notes: [
      "Seed data is intentionally blockout-first.",
      "Path collision strips should replace the long lawn placeholder surface in the path package.",
      "Cave is a separate level, not hidden inside overworld geometry.",
    ],
  },
}
